/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AresResponseDto,
  CompanyFindByNameParams,
  CompanyResponseDto,
  CompanySearchDto,
  CreateCompanyDto,
  UpdateCompanyDto
} from '.././model';





/**
 * @summary Create company
 */
export const companyCreate = (
    createCompanyDto: CreateCompanyDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompanyResponseDto>> => {
    
    
    return axios.default.post(
      `/companies`,
      createCompanyDto,options
    );
  }



export const getCompanyCreateMutationOptions = <TError = AxiosError<CompanyResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companyCreate>>, TError,{data: CreateCompanyDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof companyCreate>>, TError,{data: CreateCompanyDto}, TContext> => {

const mutationKey = ['companyCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof companyCreate>>, {data: CreateCompanyDto}> = (props) => {
          const {data} = props ?? {};

          return  companyCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CompanyCreateMutationResult = NonNullable<Awaited<ReturnType<typeof companyCreate>>>
    export type CompanyCreateMutationBody = CreateCompanyDto
    export type CompanyCreateMutationError = AxiosError<CompanyResponseDto>

    /**
 * @summary Create company
 */
export const useCompanyCreate = <TError = AxiosError<CompanyResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companyCreate>>, TError,{data: CreateCompanyDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof companyCreate>>,
        TError,
        {data: CreateCompanyDto},
        TContext
      > => {

      const mutationOptions = getCompanyCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update company
 */
export const companyUpdate = (
    updateCompanyDto: UpdateCompanyDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompanyResponseDto>> => {
    
    
    return axios.default.patch(
      `/companies`,
      updateCompanyDto,options
    );
  }



export const getCompanyUpdateMutationOptions = <TError = AxiosError<CompanyResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companyUpdate>>, TError,{data: UpdateCompanyDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof companyUpdate>>, TError,{data: UpdateCompanyDto}, TContext> => {

const mutationKey = ['companyUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof companyUpdate>>, {data: UpdateCompanyDto}> = (props) => {
          const {data} = props ?? {};

          return  companyUpdate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CompanyUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof companyUpdate>>>
    export type CompanyUpdateMutationBody = UpdateCompanyDto
    export type CompanyUpdateMutationError = AxiosError<CompanyResponseDto>

    /**
 * @summary Update company
 */
export const useCompanyUpdate = <TError = AxiosError<CompanyResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companyUpdate>>, TError,{data: UpdateCompanyDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof companyUpdate>>,
        TError,
        {data: UpdateCompanyDto},
        TContext
      > => {

      const mutationOptions = getCompanyUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List companies by user
 */
export const companyListByUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompanyResponseDto[]>> => {
    
    
    return axios.default.get(
      `/companies/list`,options
    );
  }




export const getCompanyListByUserQueryKey = () => {
    return [
    `/companies/list`
    ] as const;
    }

    
export const getCompanyListByUserQueryOptions = <TData = Awaited<ReturnType<typeof companyListByUser>>, TError = AxiosError<CompanyResponseDto[]>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyListByUser>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompanyListByUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof companyListByUser>>> = ({ signal }) => companyListByUser({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof companyListByUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompanyListByUserQueryResult = NonNullable<Awaited<ReturnType<typeof companyListByUser>>>
export type CompanyListByUserQueryError = AxiosError<CompanyResponseDto[]>


export function useCompanyListByUser<TData = Awaited<ReturnType<typeof companyListByUser>>, TError = AxiosError<CompanyResponseDto[]>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyListByUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyListByUser>>,
          TError,
          Awaited<ReturnType<typeof companyListByUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompanyListByUser<TData = Awaited<ReturnType<typeof companyListByUser>>, TError = AxiosError<CompanyResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyListByUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyListByUser>>,
          TError,
          Awaited<ReturnType<typeof companyListByUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompanyListByUser<TData = Awaited<ReturnType<typeof companyListByUser>>, TError = AxiosError<CompanyResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyListByUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List companies by user
 */

export function useCompanyListByUser<TData = Awaited<ReturnType<typeof companyListByUser>>, TError = AxiosError<CompanyResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyListByUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompanyListByUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get company by id
 */
export const companyGet = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompanyResponseDto>> => {
    
    
    return axios.default.get(
      `/companies/${id}`,options
    );
  }




export const getCompanyGetQueryKey = (id?: string,) => {
    return [
    `/companies/${id}`
    ] as const;
    }

    
export const getCompanyGetQueryOptions = <TData = Awaited<ReturnType<typeof companyGet>>, TError = AxiosError<CompanyResponseDto>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompanyGetQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof companyGet>>> = ({ signal }) => companyGet(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof companyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompanyGetQueryResult = NonNullable<Awaited<ReturnType<typeof companyGet>>>
export type CompanyGetQueryError = AxiosError<CompanyResponseDto>


export function useCompanyGet<TData = Awaited<ReturnType<typeof companyGet>>, TError = AxiosError<CompanyResponseDto>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyGet>>,
          TError,
          Awaited<ReturnType<typeof companyGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompanyGet<TData = Awaited<ReturnType<typeof companyGet>>, TError = AxiosError<CompanyResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyGet>>,
          TError,
          Awaited<ReturnType<typeof companyGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompanyGet<TData = Awaited<ReturnType<typeof companyGet>>, TError = AxiosError<CompanyResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get company by id
 */

export function useCompanyGet<TData = Awaited<ReturnType<typeof companyGet>>, TError = AxiosError<CompanyResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompanyGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Find companies by name (partial, diacritic-insensitive)
 */
export const companyFindByName = (
    params: CompanyFindByNameParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompanyResponseDto[]>> => {
    
    
    return axios.default.get(
      `/companies/findByName`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getCompanyFindByNameQueryKey = (params?: CompanyFindByNameParams,) => {
    return [
    `/companies/findByName`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCompanyFindByNameQueryOptions = <TData = Awaited<ReturnType<typeof companyFindByName>>, TError = AxiosError<CompanyResponseDto[]>>(params: CompanyFindByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyFindByName>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompanyFindByNameQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof companyFindByName>>> = ({ signal }) => companyFindByName(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof companyFindByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompanyFindByNameQueryResult = NonNullable<Awaited<ReturnType<typeof companyFindByName>>>
export type CompanyFindByNameQueryError = AxiosError<CompanyResponseDto[]>


export function useCompanyFindByName<TData = Awaited<ReturnType<typeof companyFindByName>>, TError = AxiosError<CompanyResponseDto[]>>(
 params: CompanyFindByNameParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyFindByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyFindByName>>,
          TError,
          Awaited<ReturnType<typeof companyFindByName>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompanyFindByName<TData = Awaited<ReturnType<typeof companyFindByName>>, TError = AxiosError<CompanyResponseDto[]>>(
 params: CompanyFindByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyFindByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyFindByName>>,
          TError,
          Awaited<ReturnType<typeof companyFindByName>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompanyFindByName<TData = Awaited<ReturnType<typeof companyFindByName>>, TError = AxiosError<CompanyResponseDto[]>>(
 params: CompanyFindByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyFindByName>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Find companies by name (partial, diacritic-insensitive)
 */

export function useCompanyFindByName<TData = Awaited<ReturnType<typeof companyFindByName>>, TError = AxiosError<CompanyResponseDto[]>>(
 params: CompanyFindByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyFindByName>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompanyFindByNameQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Search in ARES
 */
export const companySearch = (
    companySearchDto: CompanySearchDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AresResponseDto>> => {
    
    
    return axios.default.post(
      `/companies/search`,
      companySearchDto,options
    );
  }



export const getCompanySearchMutationOptions = <TError = AxiosError<AresResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companySearch>>, TError,{data: CompanySearchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof companySearch>>, TError,{data: CompanySearchDto}, TContext> => {

const mutationKey = ['companySearch'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof companySearch>>, {data: CompanySearchDto}> = (props) => {
          const {data} = props ?? {};

          return  companySearch(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CompanySearchMutationResult = NonNullable<Awaited<ReturnType<typeof companySearch>>>
    export type CompanySearchMutationBody = CompanySearchDto
    export type CompanySearchMutationError = AxiosError<AresResponseDto>

    /**
 * @summary Search in ARES
 */
export const useCompanySearch = <TError = AxiosError<AresResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companySearch>>, TError,{data: CompanySearchDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof companySearch>>,
        TError,
        {data: CompanySearchDto},
        TContext
      > => {

      const mutationOptions = getCompanySearchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    