/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ChatRequestDto,
  ChatResponseDto
} from '.././model';





/**
 * @summary Chat with AI
 */
export const aiChatChat = (
    chatRequestDto: ChatRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChatResponseDto>> => {
    
    
    return axios.default.post(
      `/ai-chat/chat`,
      chatRequestDto,options
    );
  }



export const getAiChatChatMutationOptions = <TError = AxiosError<ChatResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aiChatChat>>, TError,{data: ChatRequestDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof aiChatChat>>, TError,{data: ChatRequestDto}, TContext> => {

const mutationKey = ['aiChatChat'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof aiChatChat>>, {data: ChatRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  aiChatChat(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AiChatChatMutationResult = NonNullable<Awaited<ReturnType<typeof aiChatChat>>>
    export type AiChatChatMutationBody = ChatRequestDto
    export type AiChatChatMutationError = AxiosError<ChatResponseDto>

    /**
 * @summary Chat with AI
 */
export const useAiChatChat = <TError = AxiosError<ChatResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aiChatChat>>, TError,{data: ChatRequestDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof aiChatChat>>,
        TError,
        {data: ChatRequestDto},
        TContext
      > => {

      const mutationOptions = getAiChatChatMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    