/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateTaxFilingDto,
  SubmitTaxFilingDto,
  TaxFilingDetailResponseDto,
  TaxFilingResponseDto
} from '.././model';





/**
 * @summary Create tax filing
 */
export const createTaxFiling = (
    createTaxFilingDto: CreateTaxFilingDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TaxFilingResponseDto>> => {
    
    
    return axios.default.post(
      `/tax-filings`,
      createTaxFilingDto,options
    );
  }



export const getCreateTaxFilingMutationOptions = <TError = AxiosError<TaxFilingResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaxFiling>>, TError,{data: CreateTaxFilingDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createTaxFiling>>, TError,{data: CreateTaxFilingDto}, TContext> => {

const mutationKey = ['createTaxFiling'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTaxFiling>>, {data: CreateTaxFilingDto}> = (props) => {
          const {data} = props ?? {};

          return  createTaxFiling(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTaxFilingMutationResult = NonNullable<Awaited<ReturnType<typeof createTaxFiling>>>
    export type CreateTaxFilingMutationBody = CreateTaxFilingDto
    export type CreateTaxFilingMutationError = AxiosError<TaxFilingResponseDto>

    /**
 * @summary Create tax filing
 */
export const useCreateTaxFiling = <TError = AxiosError<TaxFilingResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaxFiling>>, TError,{data: CreateTaxFilingDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTaxFiling>>,
        TError,
        {data: CreateTaxFilingDto},
        TContext
      > => {

      const mutationOptions = getCreateTaxFilingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List tax filings
 */
export const listTaxFilings = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TaxFilingResponseDto[]>> => {
    
    
    return axios.default.get(
      `/tax-filings`,options
    );
  }




export const getListTaxFilingsQueryKey = () => {
    return [
    `/tax-filings`
    ] as const;
    }

    
export const getListTaxFilingsQueryOptions = <TData = Awaited<ReturnType<typeof listTaxFilings>>, TError = AxiosError<TaxFilingResponseDto[]>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTaxFilings>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTaxFilingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTaxFilings>>> = ({ signal }) => listTaxFilings({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTaxFilings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTaxFilingsQueryResult = NonNullable<Awaited<ReturnType<typeof listTaxFilings>>>
export type ListTaxFilingsQueryError = AxiosError<TaxFilingResponseDto[]>


export function useListTaxFilings<TData = Awaited<ReturnType<typeof listTaxFilings>>, TError = AxiosError<TaxFilingResponseDto[]>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTaxFilings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTaxFilings>>,
          TError,
          Awaited<ReturnType<typeof listTaxFilings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTaxFilings<TData = Awaited<ReturnType<typeof listTaxFilings>>, TError = AxiosError<TaxFilingResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTaxFilings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTaxFilings>>,
          TError,
          Awaited<ReturnType<typeof listTaxFilings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTaxFilings<TData = Awaited<ReturnType<typeof listTaxFilings>>, TError = AxiosError<TaxFilingResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTaxFilings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List tax filings
 */

export function useListTaxFilings<TData = Awaited<ReturnType<typeof listTaxFilings>>, TError = AxiosError<TaxFilingResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTaxFilings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTaxFilingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get tax filing
 */
export const getTaxFiling = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TaxFilingDetailResponseDto>> => {
    
    
    return axios.default.get(
      `/tax-filings/${id}`,options
    );
  }




export const getGetTaxFilingQueryKey = (id?: string,) => {
    return [
    `/tax-filings/${id}`
    ] as const;
    }

    
export const getGetTaxFilingQueryOptions = <TData = Awaited<ReturnType<typeof getTaxFiling>>, TError = AxiosError<TaxFilingDetailResponseDto>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaxFiling>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaxFilingQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaxFiling>>> = ({ signal }) => getTaxFiling(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaxFiling>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaxFilingQueryResult = NonNullable<Awaited<ReturnType<typeof getTaxFiling>>>
export type GetTaxFilingQueryError = AxiosError<TaxFilingDetailResponseDto>


export function useGetTaxFiling<TData = Awaited<ReturnType<typeof getTaxFiling>>, TError = AxiosError<TaxFilingDetailResponseDto>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaxFiling>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaxFiling>>,
          TError,
          Awaited<ReturnType<typeof getTaxFiling>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaxFiling<TData = Awaited<ReturnType<typeof getTaxFiling>>, TError = AxiosError<TaxFilingDetailResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaxFiling>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaxFiling>>,
          TError,
          Awaited<ReturnType<typeof getTaxFiling>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaxFiling<TData = Awaited<ReturnType<typeof getTaxFiling>>, TError = AxiosError<TaxFilingDetailResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaxFiling>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get tax filing
 */

export function useGetTaxFiling<TData = Awaited<ReturnType<typeof getTaxFiling>>, TError = AxiosError<TaxFilingDetailResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaxFiling>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaxFilingQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Submit tax filing
 */
export const submitTaxFiling = (
    id: string,
    submitTaxFilingDto: SubmitTaxFilingDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TaxFilingResponseDto>> => {
    
    
    return axios.default.post(
      `/tax-filings/${id}/submit`,
      submitTaxFilingDto,options
    );
  }



export const getSubmitTaxFilingMutationOptions = <TError = AxiosError<TaxFilingResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitTaxFiling>>, TError,{id: string;data: SubmitTaxFilingDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof submitTaxFiling>>, TError,{id: string;data: SubmitTaxFilingDto}, TContext> => {

const mutationKey = ['submitTaxFiling'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitTaxFiling>>, {id: string;data: SubmitTaxFilingDto}> = (props) => {
          const {id,data} = props ?? {};

          return  submitTaxFiling(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SubmitTaxFilingMutationResult = NonNullable<Awaited<ReturnType<typeof submitTaxFiling>>>
    export type SubmitTaxFilingMutationBody = SubmitTaxFilingDto
    export type SubmitTaxFilingMutationError = AxiosError<TaxFilingResponseDto>

    /**
 * @summary Submit tax filing
 */
export const useSubmitTaxFiling = <TError = AxiosError<TaxFilingResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitTaxFiling>>, TError,{id: string;data: SubmitTaxFilingDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitTaxFiling>>,
        TError,
        {id: string;data: SubmitTaxFilingDto},
        TContext
      > => {

      const mutationOptions = getSubmitTaxFilingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Cancel tax filing
 */
export const cancelTaxFiling = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TaxFilingResponseDto>> => {
    
    
    return axios.default.post(
      `/tax-filings/${id}/cancel`,undefined,options
    );
  }



export const getCancelTaxFilingMutationOptions = <TError = AxiosError<TaxFilingResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelTaxFiling>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof cancelTaxFiling>>, TError,{id: string}, TContext> => {

const mutationKey = ['cancelTaxFiling'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelTaxFiling>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  cancelTaxFiling(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelTaxFilingMutationResult = NonNullable<Awaited<ReturnType<typeof cancelTaxFiling>>>
    
    export type CancelTaxFilingMutationError = AxiosError<TaxFilingResponseDto>

    /**
 * @summary Cancel tax filing
 */
export const useCancelTaxFiling = <TError = AxiosError<TaxFilingResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelTaxFiling>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelTaxFiling>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCancelTaxFilingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Download VAT return XML
 */
export const downloadTaxFilingVatXml = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/tax-filings/${id}/vat-xml`,options
    );
  }




export const getDownloadTaxFilingVatXmlQueryKey = (id?: string,) => {
    return [
    `/tax-filings/${id}/vat-xml`
    ] as const;
    }

    
export const getDownloadTaxFilingVatXmlQueryOptions = <TData = Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadTaxFilingVatXmlQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadTaxFilingVatXml>>> = ({ signal }) => downloadTaxFilingVatXml(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadTaxFilingVatXmlQueryResult = NonNullable<Awaited<ReturnType<typeof downloadTaxFilingVatXml>>>
export type DownloadTaxFilingVatXmlQueryError = AxiosError<unknown>


export function useDownloadTaxFilingVatXml<TData = Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadTaxFilingVatXml>>,
          TError,
          Awaited<ReturnType<typeof downloadTaxFilingVatXml>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadTaxFilingVatXml<TData = Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadTaxFilingVatXml>>,
          TError,
          Awaited<ReturnType<typeof downloadTaxFilingVatXml>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadTaxFilingVatXml<TData = Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download VAT return XML
 */

export function useDownloadTaxFilingVatXml<TData = Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingVatXml>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadTaxFilingVatXmlQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Download VAT control statement XML
 */
export const downloadTaxFilingKhXml = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/tax-filings/${id}/kh-xml`,options
    );
  }




export const getDownloadTaxFilingKhXmlQueryKey = (id?: string,) => {
    return [
    `/tax-filings/${id}/kh-xml`
    ] as const;
    }

    
export const getDownloadTaxFilingKhXmlQueryOptions = <TData = Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadTaxFilingKhXmlQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadTaxFilingKhXml>>> = ({ signal }) => downloadTaxFilingKhXml(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadTaxFilingKhXmlQueryResult = NonNullable<Awaited<ReturnType<typeof downloadTaxFilingKhXml>>>
export type DownloadTaxFilingKhXmlQueryError = AxiosError<unknown>


export function useDownloadTaxFilingKhXml<TData = Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadTaxFilingKhXml>>,
          TError,
          Awaited<ReturnType<typeof downloadTaxFilingKhXml>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadTaxFilingKhXml<TData = Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadTaxFilingKhXml>>,
          TError,
          Awaited<ReturnType<typeof downloadTaxFilingKhXml>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadTaxFilingKhXml<TData = Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download VAT control statement XML
 */

export function useDownloadTaxFilingKhXml<TData = Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTaxFilingKhXml>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadTaxFilingKhXmlQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



