/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUserDto,
  EmailAvailableParams,
  UserResponseDto
} from '.././model';





/**
 * @summary Create user
 */
export const userCreate = (
    createUserDto: CreateUserDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponseDto>> => {
    
    
    return axios.default.post(
      `/users`,
      createUserDto,options
    );
  }



export const getUserCreateMutationOptions = <TError = AxiosError<UserResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userCreate>>, TError,{data: CreateUserDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userCreate>>, TError,{data: CreateUserDto}, TContext> => {

const mutationKey = ['userCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userCreate>>, {data: CreateUserDto}> = (props) => {
          const {data} = props ?? {};

          return  userCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserCreateMutationResult = NonNullable<Awaited<ReturnType<typeof userCreate>>>
    export type UserCreateMutationBody = CreateUserDto
    export type UserCreateMutationError = AxiosError<UserResponseDto>

    /**
 * @summary Create user
 */
export const useUserCreate = <TError = AxiosError<UserResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userCreate>>, TError,{data: CreateUserDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userCreate>>,
        TError,
        {data: CreateUserDto},
        TContext
      > => {

      const mutationOptions = getUserCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Check email available
 */
export const emailAvailable = (
    params: EmailAvailableParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<boolean>> => {
    
    
    return axios.default.get(
      `/users/emailAvailable`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getEmailAvailableQueryKey = (params?: EmailAvailableParams,) => {
    return [
    `/users/emailAvailable`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getEmailAvailableQueryOptions = <TData = Awaited<ReturnType<typeof emailAvailable>>, TError = AxiosError<boolean>>(params: EmailAvailableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof emailAvailable>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEmailAvailableQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof emailAvailable>>> = ({ signal }) => emailAvailable(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof emailAvailable>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EmailAvailableQueryResult = NonNullable<Awaited<ReturnType<typeof emailAvailable>>>
export type EmailAvailableQueryError = AxiosError<boolean>


export function useEmailAvailable<TData = Awaited<ReturnType<typeof emailAvailable>>, TError = AxiosError<boolean>>(
 params: EmailAvailableParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof emailAvailable>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof emailAvailable>>,
          TError,
          Awaited<ReturnType<typeof emailAvailable>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEmailAvailable<TData = Awaited<ReturnType<typeof emailAvailable>>, TError = AxiosError<boolean>>(
 params: EmailAvailableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof emailAvailable>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof emailAvailable>>,
          TError,
          Awaited<ReturnType<typeof emailAvailable>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEmailAvailable<TData = Awaited<ReturnType<typeof emailAvailable>>, TError = AxiosError<boolean>>(
 params: EmailAvailableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof emailAvailable>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Check email available
 */

export function useEmailAvailable<TData = Awaited<ReturnType<typeof emailAvailable>>, TError = AxiosError<boolean>>(
 params: EmailAvailableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof emailAvailable>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEmailAvailableQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




