/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUserCompanyDto,
  UpdateUserCompanyRoleDto,
  UserCompanyResponseDto
} from '.././model';





/**
 * @summary List current user memberships
 */
export const listMyMemberships = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserCompanyResponseDto[]>> => {
    
    
    return axios.default.get(
      `/user-companies/mine`,options
    );
  }




export const getListMyMembershipsQueryKey = () => {
    return [
    `/user-companies/mine`
    ] as const;
    }

    
export const getListMyMembershipsQueryOptions = <TData = Awaited<ReturnType<typeof listMyMemberships>>, TError = AxiosError<UserCompanyResponseDto[]>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyMemberships>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMyMembershipsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyMemberships>>> = ({ signal }) => listMyMemberships({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMyMemberships>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMyMembershipsQueryResult = NonNullable<Awaited<ReturnType<typeof listMyMemberships>>>
export type ListMyMembershipsQueryError = AxiosError<UserCompanyResponseDto[]>


export function useListMyMemberships<TData = Awaited<ReturnType<typeof listMyMemberships>>, TError = AxiosError<UserCompanyResponseDto[]>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyMemberships>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyMemberships>>,
          TError,
          Awaited<ReturnType<typeof listMyMemberships>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMyMemberships<TData = Awaited<ReturnType<typeof listMyMemberships>>, TError = AxiosError<UserCompanyResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyMemberships>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyMemberships>>,
          TError,
          Awaited<ReturnType<typeof listMyMemberships>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMyMemberships<TData = Awaited<ReturnType<typeof listMyMemberships>>, TError = AxiosError<UserCompanyResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyMemberships>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List current user memberships
 */

export function useListMyMemberships<TData = Awaited<ReturnType<typeof listMyMemberships>>, TError = AxiosError<UserCompanyResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyMemberships>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMyMembershipsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary List members of the active company
 */
export const listMembers = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserCompanyResponseDto[]>> => {
    
    
    return axios.default.get(
      `/user-companies`,options
    );
  }




export const getListMembersQueryKey = () => {
    return [
    `/user-companies`
    ] as const;
    }

    
export const getListMembersQueryOptions = <TData = Awaited<ReturnType<typeof listMembers>>, TError = AxiosError<UserCompanyResponseDto[]>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMembersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMembers>>> = ({ signal }) => listMembers({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMembersQueryResult = NonNullable<Awaited<ReturnType<typeof listMembers>>>
export type ListMembersQueryError = AxiosError<UserCompanyResponseDto[]>


export function useListMembers<TData = Awaited<ReturnType<typeof listMembers>>, TError = AxiosError<UserCompanyResponseDto[]>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembers>>,
          TError,
          Awaited<ReturnType<typeof listMembers>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembers<TData = Awaited<ReturnType<typeof listMembers>>, TError = AxiosError<UserCompanyResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembers>>,
          TError,
          Awaited<ReturnType<typeof listMembers>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembers<TData = Awaited<ReturnType<typeof listMembers>>, TError = AxiosError<UserCompanyResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List members of the active company
 */

export function useListMembers<TData = Awaited<ReturnType<typeof listMembers>>, TError = AxiosError<UserCompanyResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMembersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Invite existing user to active company
 */
export const inviteMember = (
    createUserCompanyDto: CreateUserCompanyDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserCompanyResponseDto>> => {
    
    
    return axios.default.post(
      `/user-companies/invite`,
      createUserCompanyDto,options
    );
  }



export const getInviteMemberMutationOptions = <TError = AxiosError<UserCompanyResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inviteMember>>, TError,{data: CreateUserCompanyDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inviteMember>>, TError,{data: CreateUserCompanyDto}, TContext> => {

const mutationKey = ['inviteMember'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inviteMember>>, {data: CreateUserCompanyDto}> = (props) => {
          const {data} = props ?? {};

          return  inviteMember(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InviteMemberMutationResult = NonNullable<Awaited<ReturnType<typeof inviteMember>>>
    export type InviteMemberMutationBody = CreateUserCompanyDto
    export type InviteMemberMutationError = AxiosError<UserCompanyResponseDto>

    /**
 * @summary Invite existing user to active company
 */
export const useInviteMember = <TError = AxiosError<UserCompanyResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inviteMember>>, TError,{data: CreateUserCompanyDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inviteMember>>,
        TError,
        {data: CreateUserCompanyDto},
        TContext
      > => {

      const mutationOptions = getInviteMemberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Change a member's role
 */
export const changeMemberRole = (
    id: string,
    updateUserCompanyRoleDto: UpdateUserCompanyRoleDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserCompanyResponseDto>> => {
    
    
    return axios.default.patch(
      `/user-companies/${id}/role`,
      updateUserCompanyRoleDto,options
    );
  }



export const getChangeMemberRoleMutationOptions = <TError = AxiosError<UserCompanyResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeMemberRole>>, TError,{id: string;data: UpdateUserCompanyRoleDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof changeMemberRole>>, TError,{id: string;data: UpdateUserCompanyRoleDto}, TContext> => {

const mutationKey = ['changeMemberRole'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeMemberRole>>, {id: string;data: UpdateUserCompanyRoleDto}> = (props) => {
          const {id,data} = props ?? {};

          return  changeMemberRole(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeMemberRoleMutationResult = NonNullable<Awaited<ReturnType<typeof changeMemberRole>>>
    export type ChangeMemberRoleMutationBody = UpdateUserCompanyRoleDto
    export type ChangeMemberRoleMutationError = AxiosError<UserCompanyResponseDto>

    /**
 * @summary Change a member's role
 */
export const useChangeMemberRole = <TError = AxiosError<UserCompanyResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeMemberRole>>, TError,{id: string;data: UpdateUserCompanyRoleDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeMemberRole>>,
        TError,
        {id: string;data: UpdateUserCompanyRoleDto},
        TContext
      > => {

      const mutationOptions = getChangeMemberRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Remove a member
 */
export const removeMember = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/user-companies/${id}`,options
    );
  }



export const getRemoveMemberMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeMember>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof removeMember>>, TError,{id: string}, TContext> => {

const mutationKey = ['removeMember'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeMember>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  removeMember(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveMemberMutationResult = NonNullable<Awaited<ReturnType<typeof removeMember>>>
    
    export type RemoveMemberMutationError = AxiosError<unknown>

    /**
 * @summary Remove a member
 */
export const useRemoveMember = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeMember>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeMember>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getRemoveMemberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    