/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  InvoiceSettingsResponseDto,
  UpdateInvoiceSettingsDto
} from '.././model';





/**
 * @summary Get invoice settings for company
 */
export const invoiceSettingsGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InvoiceSettingsResponseDto>> => {
    
    
    return axios.default.get(
      `/invoice-settings`,options
    );
  }




export const getInvoiceSettingsGetQueryKey = () => {
    return [
    `/invoice-settings`
    ] as const;
    }

    
export const getInvoiceSettingsGetQueryOptions = <TData = Awaited<ReturnType<typeof invoiceSettingsGet>>, TError = AxiosError<InvoiceSettingsResponseDto>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceSettingsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInvoiceSettingsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceSettingsGet>>> = ({ signal }) => invoiceSettingsGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof invoiceSettingsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InvoiceSettingsGetQueryResult = NonNullable<Awaited<ReturnType<typeof invoiceSettingsGet>>>
export type InvoiceSettingsGetQueryError = AxiosError<InvoiceSettingsResponseDto>


export function useInvoiceSettingsGet<TData = Awaited<ReturnType<typeof invoiceSettingsGet>>, TError = AxiosError<InvoiceSettingsResponseDto>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceSettingsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceSettingsGet>>,
          TError,
          Awaited<ReturnType<typeof invoiceSettingsGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceSettingsGet<TData = Awaited<ReturnType<typeof invoiceSettingsGet>>, TError = AxiosError<InvoiceSettingsResponseDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceSettingsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceSettingsGet>>,
          TError,
          Awaited<ReturnType<typeof invoiceSettingsGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceSettingsGet<TData = Awaited<ReturnType<typeof invoiceSettingsGet>>, TError = AxiosError<InvoiceSettingsResponseDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceSettingsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get invoice settings for company
 */

export function useInvoiceSettingsGet<TData = Awaited<ReturnType<typeof invoiceSettingsGet>>, TError = AxiosError<InvoiceSettingsResponseDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceSettingsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInvoiceSettingsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update invoice settings for company
 */
export const invoiceSettingsUpdate = (
    updateInvoiceSettingsDto: UpdateInvoiceSettingsDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InvoiceSettingsResponseDto>> => {
    
    
    return axios.default.patch(
      `/invoice-settings`,
      updateInvoiceSettingsDto,options
    );
  }



export const getInvoiceSettingsUpdateMutationOptions = <TError = AxiosError<InvoiceSettingsResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invoiceSettingsUpdate>>, TError,{data: UpdateInvoiceSettingsDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof invoiceSettingsUpdate>>, TError,{data: UpdateInvoiceSettingsDto}, TContext> => {

const mutationKey = ['invoiceSettingsUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invoiceSettingsUpdate>>, {data: UpdateInvoiceSettingsDto}> = (props) => {
          const {data} = props ?? {};

          return  invoiceSettingsUpdate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InvoiceSettingsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof invoiceSettingsUpdate>>>
    export type InvoiceSettingsUpdateMutationBody = UpdateInvoiceSettingsDto
    export type InvoiceSettingsUpdateMutationError = AxiosError<InvoiceSettingsResponseDto>

    /**
 * @summary Update invoice settings for company
 */
export const useInvoiceSettingsUpdate = <TError = AxiosError<InvoiceSettingsResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invoiceSettingsUpdate>>, TError,{data: UpdateInvoiceSettingsDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invoiceSettingsUpdate>>,
        TError,
        {data: UpdateInvoiceSettingsDto},
        TContext
      > => {

      const mutationOptions = getInvoiceSettingsUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    