/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { ChatHistoryItemDtoRole } from './chatHistoryItemDtoRole';

export interface ChatHistoryItemDto {
  role: ChatHistoryItemDtoRole;
  content: string;
}
