/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { ChatContextSnapshotDtoPurpose } from './chatContextSnapshotDtoPurpose';
import type { SelectedCompanySnapshotDto } from './selectedCompanySnapshotDto';
import type { LastCompanySearchDto } from './lastCompanySearchDto';

export interface ChatContextSnapshotDto {
  purpose: ChatContextSnapshotDtoPurpose;
  selectedCompany?: SelectedCompanySnapshotDto;
  lastCompanySearch?: LastCompanySearchDto;
}
