/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type ChatContextSnapshotDtoPurpose = typeof ChatContextSnapshotDtoPurpose[keyof typeof ChatContextSnapshotDtoPurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatContextSnapshotDtoPurpose = {
  general: 'general',
  company_creation: 'company_creation',
} as const;
