/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { ChatContextOperationsDto } from './chatContextOperationsDto';

export interface ChatRequestDto {
  /** The user message to send to the AI */
  userInput: string;
  contextOperations?: ChatContextOperationsDto;
}
