/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { ChatHistoryItemDto } from './chatHistoryItemDto';
import type { ChatContextSnapshotDto } from './chatContextSnapshotDto';
import type { ChatMetricsDto } from './chatMetricsDto';

export interface ChatResponseDto {
  /** The AI response */
  answer: string;
  history: ChatHistoryItemDto[];
  context: ChatContextSnapshotDto;
  metrics: ChatMetricsDto;
}
