/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type ChatHistoryItemDtoRole = typeof ChatHistoryItemDtoRole[keyof typeof ChatHistoryItemDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatHistoryItemDtoRole = {
  user: 'user',
  assistant: 'assistant',
} as const;
