/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type CompanyResponseDtoCompanyType = typeof CompanyResponseDtoCompanyType[keyof typeof CompanyResponseDtoCompanyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompanyResponseDtoCompanyType = {
  OSVC: 'OSVC',
  SRO: 'SRO',
} as const;
