/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { CompanyResponseDtoCompanyType } from './companyResponseDtoCompanyType';

export interface CompanyResponseDto {
  id: string;
  name?: string;
  companyName?: string;
  surname?: string;
  companyType?: CompanyResponseDtoCompanyType;
  country: string;
  email?: string;
  street?: string;
  houseNumber?: string;
  orientationNumber?: string;
  registrationNumber?: string;
  vatPayer: boolean;
  city?: string;
  psc?: string;
  ico?: string;
  dic?: string;
  description?: string;
  c_ufo?: string;
  c_pracufo?: string;
}
