/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface ContactSearchDto {
  obchodniJmeno?: string;
  ico?: string[];
  start?: number;
  pocet?: number;
  /** When true, each result is enriched with its CRPDPH VAT status and — for sole traders (právní forma 101) — the RZP proprietor name, as in getRegistrationData. */
  getDphStatus?: boolean;
}
