/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface ContactInvoiceStatsDto {
  /** Number of invoices (statuses ISSUED and PAID) */
  count: number;
  /** Sum of totalWithTax across counted invoices */
  totalWithTax: number;
  /** Average totalWithTax across counted invoices */
  averageWithTax: number;
  /** Number of unpaid invoices (status ISSUED) */
  unpaidCount: number;
  /** Sum of totalWithTax across unpaid invoices */
  unpaidTotalWithTax: number;
  /** Number of unpaid invoices past their due date */
  overdueCount: number;
  /** @nullable */
  firstInvoiceDate?: string | null;
  /** @nullable */
  lastInvoiceDate?: string | null;
}
