/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceVatClaimDto } from './invoiceVatClaimDto';

export interface CreateSimpleInvoiceDto {
  /** UUID of the external contact */
  contactId?: string;
  number: string;
  createdDate: string;
  duzpDate: string;
  total: number;
  totalTax: number;
  totalWithTax: number;
  description?: string;
  /** Optional VAT claim metadata. When omitted, no claim row is created. */
  vatClaim?: InvoiceVatClaimDto;
}
