/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { CreateInvoiceDtoType } from './createInvoiceDtoType';
import type { CreateInvoiceDtoStatus } from './createInvoiceDtoStatus';
import type { InvoiceItemDto } from './invoiceItemDto';

export interface CreateInvoiceDto {
  companyId: string;
  bankId: string;
  number: string;
  currency: string;
  /** Direction of invoice - RECEIVED or ISSUED */
  type: CreateInvoiceDtoType;
  /** Invoice status. Defaults to ISSUED when omitted. */
  status?: CreateInvoiceDtoStatus;
  exchangeRate?: number;
  createdDate: string;
  taxDate: string;
  dueDate: string;
  total: number;
  totalTax: number;
  totalWithTax: number;
  /** Array of invoice items */
  items: InvoiceItemDto[];
}
