/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Type of invoice - INCOMING or OUTGOING
 */
export type CreateInvoiceDtoType = typeof CreateInvoiceDtoType[keyof typeof CreateInvoiceDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateInvoiceDtoType = {
  INCOMING: 'INCOMING',
  OUTGOING: 'OUTGOING',
} as const;
