/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { CreatePaymentDtoPaymentMethod } from './createPaymentDtoPaymentMethod';

export interface CreatePaymentDto {
  /** UUID of the related invoice */
  invoiceId: string;
  /** UUID of the company bank account the payment went through */
  bankId?: string;
  paymentMethod: CreatePaymentDtoPaymentMethod;
  amount: number;
  currency?: string;
  paymentDate: string;
  reference?: string;
  note?: string;
  exchangeRate?: number;
}
