/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { CreateUserCompanyDtoRole } from './createUserCompanyDtoRole';

export interface CreateUserCompanyDto {
  companyId: string;
  userEmail: string;
  role: CreateUserCompanyDtoRole;
}
