/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type CreateUserCompanyDtoRole = typeof CreateUserCompanyDtoRole[keyof typeof CreateUserCompanyDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserCompanyDtoRole = {
  OWNER: 'OWNER',
  ACCOUNTANT: 'ACCOUNTANT',
  MEMBER: 'MEMBER',
} as const;
