/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Payment method of the recorded payment when paidDate is set. Defaults to BANK_TRANSFER.
 */
export type CreateInvoiceDtoPaidPaymentMethod = typeof CreateInvoiceDtoPaidPaymentMethod[keyof typeof CreateInvoiceDtoPaidPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateInvoiceDtoPaidPaymentMethod = {
  BANK_TRANSFER: 'BANK_TRANSFER',
  CASH: 'CASH',
  CARD: 'CARD',
  OTHER: 'OTHER',
} as const;
