/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Direction of invoice - RECEIVED or ISSUED
 */
export type CreateInvoiceDtoType = typeof CreateInvoiceDtoType[keyof typeof CreateInvoiceDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateInvoiceDtoType = {
  RECEIVED: 'RECEIVED',
  ISSUED: 'ISSUED',
} as const;
