/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { CreateTaxFilingDtoSubmissionType } from './createTaxFilingDtoSubmissionType';

export interface CreateTaxFilingDto {
  /**
   * @minimum 1
   * @maximum 12
   */
  month: number;
  /**
   * @minimum 1900
   * @maximum 2100
   */
  year: number;
  submissionType: CreateTaxFilingDtoSubmissionType;
  createDate: string;
}
