/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Payment method (forma úhrady). Defaults to BANK_TRANSFER.
 */
export type CreateInvoiceDtoPaymentMethod = typeof CreateInvoiceDtoPaymentMethod[keyof typeof CreateInvoiceDtoPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateInvoiceDtoPaymentMethod = {
  BANK_TRANSFER: 'BANK_TRANSFER',
  CASH: 'CASH',
  CARD: 'CARD',
  OTHER: 'OTHER',
} as const;
