/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { CreateCompanyDtoCompanyType } from './createCompanyDtoCompanyType';

export interface CreateCompanyDto {
  companyType: CreateCompanyDtoCompanyType;
  name?: string;
  surname?: string;
  companyName?: string;
  country: string;
  email?: string;
  street?: string;
  houseNumber?: string;
  orientationNumber?: string;
  registrationNumber?: string;
  vatPayer?: boolean;
  city: string;
  psc: string;
  ico: string;
  dic?: string;
  description?: string;
  c_ufo?: string;
  c_pracufo?: string;
}
