/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Invoice status. Defaults to ISSUED when omitted.
 */
export type CreateInvoiceDtoStatus = typeof CreateInvoiceDtoStatus[keyof typeof CreateInvoiceDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateInvoiceDtoStatus = {
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  OVERDUE: 'OVERDUE',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
} as const;
