/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type DashboardInvoiceItemDtoStatus = typeof DashboardInvoiceItemDtoStatus[keyof typeof DashboardInvoiceItemDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardInvoiceItemDtoStatus = {
  PAID: 'PAID',
  PENDING: 'PENDING',
} as const;
