/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface DashboardSummaryDto {
  totalIncome: number;
  totalExpenses: number;
  netBalance: number;
  activeClients: number;
  newClientsThisMonth: number;
  incomeChangePct: number;
  expenseChangePct: number;
  netChangePct: number;
}
