/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { DashboardSummaryDto } from './dashboardSummaryDto';
import type { DashboardInvoiceItemDto } from './dashboardInvoiceItemDto';

export interface DashboardStatsResponseDto {
  summary: DashboardSummaryDto;
  recentIncomingInvoices: DashboardInvoiceItemDto[];
  recentOutgoingInvoices: DashboardInvoiceItemDto[];
}
