/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type DataMessageDtoDirection = typeof DataMessageDtoDirection[keyof typeof DataMessageDtoDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataMessageDtoDirection = {
  SENT: 'SENT',
  RECEIVED: 'RECEIVED',
} as const;
