/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type DataMessageDtoState = typeof DataMessageDtoState[keyof typeof DataMessageDtoState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataMessageDtoState = {
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  READ: 'READ',
  FAILED: 'FAILED',
  UNKNOWN: 'UNKNOWN',
} as const;
