/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * ISDS dmStatusCode from the send
 * @nullable
 */
export type DataMessageDtoStatusCode = { [key: string]: unknown } | null;
