/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { DataMessageDtoDirection } from './dataMessageDtoDirection';
import type { DataMessageDtoState } from './dataMessageDtoState';
import type { MessageStatusEventDto } from './messageStatusEventDto';

export interface DataMessageDto {
  /** Internal record ID */
  id: string;
  /**
   * ISDS message ID (dmID) — null when the send failed
   * @nullable
   */
  messageId: string | null;
  direction: DataMessageDtoDirection;
  /** Recipient data box ID */
  recipient: string;
  /**
   * Tax filing this message submitted, if any
   * @nullable
   */
  taxFilingId: string | null;
  /** Message subject */
  subject: string;
  state: DataMessageDtoState;
  /**
   * ISDS dmStatusCode from the send
   * @nullable
   */
  statusCode: string | null;
  /**
   * ISDS dmStatusMessage — the failure reason when failed
   * @nullable
   */
  statusMessage: string | null;
  /**
   * Raw ISDS dmMessageStatus code
   * @nullable
   */
  rawStateCode: number | null;
  /** When the message was sent (ISO 8601) */
  sentAt: string;
  /**
   * Legal-service time, doručeno — dmAcceptanceTime (ISO 8601)
   * @nullable
   */
  deliveredAt: string | null;
  /**
   * Delivery-to-data-box time, dodáno — dmDeliveryTime (ISO 8601)
   * @nullable
   */
  servedAt: string | null;
  /** Persisted ISDS delivery event timeline (last refresh) */
  events: MessageStatusEventDto[];
}
