/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Bank code (kód banky).
 * @nullable
 */
export type DphBankAccountDtoBankCode = { [key: string]: unknown } | null;
