/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * IBAN, for foreign accounts.
 * @nullable
 */
export type DphBankAccountDtoIban = { [key: string]: unknown } | null;
