/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Human-readable account, e.g. "19-2000145399/0800" or the IBAN.
 * @nullable
 */
export type DphBankAccountDtoFormatted = { [key: string]: unknown } | null;
