/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { DphBankAccountDtoPrefix } from './dphBankAccountDtoPrefix';
import type { DphBankAccountDtoNumber } from './dphBankAccountDtoNumber';
import type { DphBankAccountDtoBankCode } from './dphBankAccountDtoBankCode';
import type { DphBankAccountDtoIban } from './dphBankAccountDtoIban';
import type { DphBankAccountDtoFormatted } from './dphBankAccountDtoFormatted';

export interface DphBankAccountDto {
  /** Date the account was published (ISO date). */
  publishedAt: string;
  /** True for a standard domestic account, false for non-standard. */
  standard: boolean;
  /**
   * Account prefix (předčíslí).
   * @nullable
   */
  prefix: DphBankAccountDtoPrefix;
  /**
   * Domestic account number.
   * @nullable
   */
  number: DphBankAccountDtoNumber;
  /**
   * Bank code (kód banky).
   * @nullable
   */
  bankCode: DphBankAccountDtoBankCode;
  /**
   * IBAN, for foreign accounts.
   * @nullable
   */
  iban: DphBankAccountDtoIban;
  /**
   * Human-readable account, e.g. "19-2000145399/0800" or the IBAN.
   * @nullable
   */
  formatted: DphBankAccountDtoFormatted;
}
