/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { SidloDto } from './sidloDto';
import type { AdresaDorucovaciDto } from './adresaDorucovaciDto';

export interface EkonomickySubjektDto {
  ico: string;
  obchodniJmeno: string;
  sidlo: SidloDto;
  pravniForma: string;
  financniUrad: string;
  datumVzniku: string;
  datumAktualizace: string;
  dic: string;
  icoId: string;
  adresaDorucovaci: AdresaDorucovaciDto;
}
