/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type InvoiceListByUserType = typeof InvoiceListByUserType[keyof typeof InvoiceListByUserType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceListByUserType = {
  INCOMING: 'INCOMING',
  OUTGOING: 'OUTGOING',
} as const;
