/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceVatClaimResponseDtoClaimType } from './invoiceVatClaimResponseDtoClaimType';
import type { InvoiceVatClaimResponseDtoClaimRatio } from './invoiceVatClaimResponseDtoClaimRatio';
import type { InvoiceVatClaimResponseDtoStatus } from './invoiceVatClaimResponseDtoStatus';
import type { InvoiceVatClaimResponseDtoNote } from './invoiceVatClaimResponseDtoNote';

export interface InvoiceVatClaimResponseDto {
  id: string;
  invoiceId: string;
  companyId: string;
  shouldClaimVat: boolean;
  /** @nullable */
  claimType?: InvoiceVatClaimResponseDtoClaimType;
  /** @nullable */
  claimRatio?: InvoiceVatClaimResponseDtoClaimRatio;
  /** @nullable */
  claimMonth?: string | null;
  status: InvoiceVatClaimResponseDtoStatus;
  /** @nullable */
  claimedAt?: string | null;
  /** @nullable */
  note?: InvoiceVatClaimResponseDtoNote;
  createdAt: string;
  updatedAt: string;
}
