/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceListByUserType } from './invoiceListByUserType';

export type InvoiceListByUserParams = {
/**
 * Filter by invoice type
 */
type?: InvoiceListByUserType;
/**
 * Page number (default: 1)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page (default: 10)
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
};
