/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { ParsedBankAccountDto } from './parsedBankAccountDto';

/**
 * The supplier's account; received invoices only
 * @nullable
 */
export type InvoiceParseDataDtoBankAccount = ParsedBankAccountDto | null;
