/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type InvoiceVatClaimResponseDtoStatus = typeof InvoiceVatClaimResponseDtoStatus[keyof typeof InvoiceVatClaimResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceVatClaimResponseDtoStatus = {
  PENDING: 'PENDING',
  CLAIMED: 'CLAIMED',
  SKIPPED: 'SKIPPED',
} as const;
