/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type InvoiceListByCompanyType = typeof InvoiceListByCompanyType[keyof typeof InvoiceListByCompanyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceListByCompanyType = {
  RECEIVED: 'RECEIVED',
  ISSUED: 'ISSUED',
} as const;
