/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface InvoiceItemResponseDto {
  id: string;
  name: string;
  quantity: string;
  unitPrice: string;
  total: string;
  vatRate?: string;
  createdAt: string;
}
