/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type InvoiceResponseDtoVatClaimType = typeof InvoiceResponseDtoVatClaimType[keyof typeof InvoiceResponseDtoVatClaimType] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceResponseDtoVatClaimType = {
  FULL: 'FULL',
  PARTIAL: 'PARTIAL',
} as const;
