/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type InvoiceListByUserType = typeof InvoiceListByUserType[keyof typeof InvoiceListByUserType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceListByUserType = {
  RECEIVED: 'RECEIVED',
  ISSUED: 'ISSUED',
} as const;
