/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceItemDto } from './invoiceItemDto';
import type { BankResponseDto } from './bankResponseDto';
import type { CompanyResponseDto } from './companyResponseDto';

export interface InvoiceResponseDto {
  id: string;
  number: string;
  createdDate: string;
  taxDate: string;
  dueDate: string;
  total: number;
  totalTax: number;
  exchangeRate?: number;
  currency: string;
  type: string;
  totalWithTax: number;
  items: InvoiceItemDto[];
  bank: BankResponseDto;
  company: CompanyResponseDto;
}
