/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type InvoiceResponseDtoVatClaimStatus = typeof InvoiceResponseDtoVatClaimStatus[keyof typeof InvoiceResponseDtoVatClaimStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceResponseDtoVatClaimStatus = {
  PENDING: 'PENDING',
  CLAIMED: 'CLAIMED',
  SKIPPED: 'SKIPPED',
} as const;
