/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceGetVatByMonthDefaultPayable } from './invoiceGetVatByMonthDefaultPayable';
import type { InvoiceGetVatByMonthDefaultDeductible } from './invoiceGetVatByMonthDefaultDeductible';

export type InvoiceGetVatByMonthDefault = {
  payable?: InvoiceGetVatByMonthDefaultPayable;
  deductible?: InvoiceGetVatByMonthDefaultDeductible;
};
