/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface InvoiceItemDto {
  name: string;
  pricePerUnit: number;
  units: number;
  /** VAT percentage */
  vat: number;
  amount: number;
}
