/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { ParsedInvoiceType } from './parsedInvoiceType';
import type { ParsedInvoiceTypeSource } from './parsedInvoiceTypeSource';
import type { ParsedPartyDto } from './parsedPartyDto';
import type { VatBreakdownItemDto } from './vatBreakdownItemDto';
import type { InvoiceParseDataDtoBankAccount } from './invoiceParseDataDtoBankAccount';
import type { ParsedInvoiceItemDto } from './parsedInvoiceItemDto';

export interface InvoiceParseDataDto {
  type: ParsedInvoiceType;
  /** How type was decided: the company's own IČO/DIČ on the document (MATCH), the model's guess (MODEL) or the RECEIVED default (DEFAULT) */
  typeSource: ParsedInvoiceTypeSource;
  /** The other party: supplier of a received invoice, customer of an issued one */
  counterparty: ParsedPartyDto;
  /** @nullable */
  documentNumber: string | null;
  /** @nullable */
  variableSymbol: string | null;
  /**
   * YYYY-MM-DD
   * @nullable
   */
  issueDate: string | null;
  /**
   * DUZP, YYYY-MM-DD
   * @nullable
   */
  taxDate: string | null;
  /**
   * YYYY-MM-DD
   * @nullable
   */
  dueDate: string | null;
  /** @nullable */
  currency: string | null;
  /** @nullable */
  total: number | null;
  /** @nullable */
  vat: number | null;
  vatBreakdown: VatBreakdownItemDto[];
  /**
   * The supplier's account; received invoices only
   * @nullable
   */
  bankAccount: InvoiceParseDataDtoBankAccount;
  reverseCharge: boolean;
  /** Line items; issued invoices only */
  items: ParsedInvoiceItemDto[];
}
