/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceListByCompanyType } from './invoiceListByCompanyType';

export type InvoiceListByCompanyParams = {
/**
 * Filter by invoice type - RECEIVED or ISSUED
 */
type?: InvoiceListByCompanyType;
/**
 * Page number (default: 1)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page (default: 10)
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
};
