/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * New field value after the change
 * @nullable
 */
export type InvoiceStatusHistoryChangeDtoNewValue = { [key: string]: unknown } | null;
