/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceResponseDtoVatMode } from './invoiceResponseDtoVatMode';
import type { InvoiceResponseDtoStatus } from './invoiceResponseDtoStatus';
import type { InvoiceResponseDtoKind } from './invoiceResponseDtoKind';
import type { InvoiceItemResponseDto } from './invoiceItemResponseDto';
import type { ContactSnapshotDto } from './contactSnapshotDto';
import type { InvoiceBankAccountSnapshotDto } from './invoiceBankAccountSnapshotDto';
import type { PaymentResponseDto } from './paymentResponseDto';
import type { InvoiceStatusHistoryItemDto } from './invoiceStatusHistoryItemDto';
import type { InvoiceResponseDtoVatClaimType } from './invoiceResponseDtoVatClaimType';
import type { InvoiceResponseDtoVatClaimRatio } from './invoiceResponseDtoVatClaimRatio';
import type { InvoiceResponseDtoVatClaimStatus } from './invoiceResponseDtoVatClaimStatus';
import type { InvoiceResponseDtoVatClaimNote } from './invoiceResponseDtoVatClaimNote';

export interface InvoiceResponseDto {
  id: string;
  number: string;
  createdDate: string;
  duzpDate: string;
  dueDate?: string;
  total: number;
  totalTax: number;
  exchangeRate?: number;
  currency?: string;
  type: string;
  vatMode?: InvoiceResponseDtoVatMode;
  status: InvoiceResponseDtoStatus;
  kind: InvoiceResponseDtoKind;
  description?: string;
  totalWithTax: number;
  items: InvoiceItemResponseDto[];
  companyId: string;
  bankId?: string;
  contactId?: string;
  variableSymbol?: string;
  specificSymbol?: string;
  konstantSymbol?: string;
  note?: string;
  internalNote?: string;
  originalNumber?: string;
  contactSnapshot?: ContactSnapshotDto;
  bankAccount?: InvoiceBankAccountSnapshotDto;
  payments?: PaymentResponseDto[];
  statusHistory?: InvoiceStatusHistoryItemDto[];
  /** @nullable */
  vatClaimType?: InvoiceResponseDtoVatClaimType;
  /** @nullable */
  vatClaimRatio?: InvoiceResponseDtoVatClaimRatio;
  /** @nullable */
  vatClaimMonth?: string | null;
  /** @nullable */
  vatClaimStatus?: InvoiceResponseDtoVatClaimStatus;
  /** @nullable */
  vatClaimedAt?: string | null;
  /** @nullable */
  vatClaimNote?: InvoiceResponseDtoVatClaimNote;
}
