/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceVatClaimDtoClaimType } from './invoiceVatClaimDtoClaimType';

export interface InvoiceVatClaimDto {
  /** Whether the company intends to claim VAT deduction for this invoice. When false, status is set to SKIPPED automatically. */
  shouldClaimVat?: boolean;
  /** FULL = 100% deduction, PARTIAL = ratio in (0,1). Required when shouldClaimVat=true. */
  claimType?: InvoiceVatClaimDtoClaimType;
  /** Required when claimType=PARTIAL. Must be in (0,1). Ignored for FULL. */
  claimRatio?: number;
  /** First day of the month in which VAT is claimed (YYYY-MM-01). */
  claimMonth?: string;
  /** Internal note about the VAT claim. */
  note?: string;
}
