/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceResponseDtoStatus } from './invoiceResponseDtoStatus';
import type { InvoiceItemResponseDto } from './invoiceItemResponseDto';
import type { ContactSnapshotDto } from './contactSnapshotDto';
import type { InvoiceBankAccountSnapshotDto } from './invoiceBankAccountSnapshotDto';
import type { PaymentResponseDto } from './paymentResponseDto';
import type { InvoiceStatusHistoryItemDto } from './invoiceStatusHistoryItemDto';

export interface InvoiceResponseDto {
  id: string;
  number: string;
  createdDate: string;
  taxDate: string;
  dueDate: string;
  total: number;
  totalTax: number;
  exchangeRate?: number;
  currency: string;
  type: string;
  status: InvoiceResponseDtoStatus;
  totalWithTax: number;
  items: InvoiceItemResponseDto[];
  companyId: string;
  bankId: string;
  contactId: string;
  contactSnapshot?: ContactSnapshotDto;
  bankAccount?: InvoiceBankAccountSnapshotDto;
  payments?: PaymentResponseDto[];
  statusHistory?: InvoiceStatusHistoryItemDto[];
}
