/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceStatusHistoryChangeDtoOriginalValue } from './invoiceStatusHistoryChangeDtoOriginalValue';
import type { InvoiceStatusHistoryChangeDtoNewValue } from './invoiceStatusHistoryChangeDtoNewValue';

export interface InvoiceStatusHistoryChangeDto {
  item: string;
  /**
   * Original field value before the change
   * @nullable
   */
  originalValue?: InvoiceStatusHistoryChangeDtoOriginalValue;
  /**
   * New field value after the change
   * @nullable
   */
  newValue?: InvoiceStatusHistoryChangeDtoNewValue;
}
