/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface IsdsSettingsDto {
  /**
   * ISDS login username, or null when not configured
   * @nullable
   */
  username: string | null;
  /** Whether an ISDS password is stored */
  hasPassword: boolean;
}
