/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface IsdsOwnerDto {
  /**
   * Data box identifier (dbID)
   * @nullable
   */
  dbID: string | null;
  /**
   * Data box type (e.g. PFO, PO, OVM)
   * @nullable
   */
  dbType: string | null;
  /**
   * Owner display name (company name or person full name)
   * @nullable
   */
  name: string | null;
}
