/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Owner display name (company name or person full name)
 * @nullable
 */
export type IsdsOwnerDtoName = { [key: string]: unknown } | null;
