/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Data box type (e.g. PFO, PO, OVM)
 * @nullable
 */
export type IsdsOwnerDtoDbType = { [key: string]: unknown } | null;
