/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type LastCompanySearchDtoSource = typeof LastCompanySearchDtoSource[keyof typeof LastCompanySearchDtoSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LastCompanySearchDtoSource = {
  local: 'local',
  ares: 'ares',
} as const;
