/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { LastCompanySearchDtoSource } from './lastCompanySearchDtoSource';
import type { LastCompanySearchItemDto } from './lastCompanySearchItemDto';

export interface LastCompanySearchDto {
  source: LastCompanySearchDtoSource;
  query: string;
  count: number;
  items: LastCompanySearchItemDto[];
  timestamp: number;
}
