/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type ListVatClaimsDtoStatus = typeof ListVatClaimsDtoStatus[keyof typeof ListVatClaimsDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListVatClaimsDtoStatus = {
  PENDING: 'PENDING',
  CLAIMED: 'CLAIMED',
  SKIPPED: 'SKIPPED',
} as const;
