/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { ListVatClaimsDtoStatus } from './listVatClaimsDtoStatus';

export interface ListVatClaimsDto {
  /**
   * Year (YYYY)
   * @minimum 1900
   * @maximum 2100
   */
  year: number;
  /**
   * Month (1-12)
   * @minimum 1
   * @maximum 12
   */
  month: number;
  status?: ListVatClaimsDtoStatus;
}
