/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { MarkVatClaimedDtoClaimType } from './markVatClaimedDtoClaimType';

export interface MarkVatClaimedDto {
  /** Month in which the VAT was claimed (first day of the month). */
  claimMonth: string;
  claimType?: MarkVatClaimedDtoClaimType;
  claimRatio?: number;
  note?: string;
}
