/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * When the message was delivered to the data box (ISO 8601)
 * @nullable
 */
export type MessageStatusResponseDtoDeliveredAt = { [key: string]: unknown } | null;
