/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface MessageStatusEventDto {
  /**
   * ISDS event timestamp (dmEventTime)
   * @nullable
   */
  time: string | null;
  /**
   * ISDS event description (dmEventDescr)
   * @nullable
   */
  description: string | null;
}
