/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * ISDS event timestamp (dmEventTime)
 * @nullable
 */
export type MessageStatusEventDtoTime = { [key: string]: unknown } | null;
