/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * ISDS dmStatusMessage — the failure reason when failed
 * @nullable
 */
export type MessageStatusResponseDtoStatusMessage = { [key: string]: unknown } | null;
