/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { MessageStatusResponseDtoState } from './messageStatusResponseDtoState';
import type { MessageStatusEventDto } from './messageStatusEventDto';

export interface MessageStatusResponseDto {
  /** DataMessage record ID */
  id: string;
  /**
   * ISDS message ID (dmID) — null when the send failed
   * @nullable
   */
  messageId: string | null;
  /** Derived lifecycle state */
  state: MessageStatusResponseDtoState;
  /**
   * ISDS dmStatusCode from the send
   * @nullable
   */
  statusCode: string | null;
  /**
   * ISDS dmStatusMessage — the failure reason when failed
   * @nullable
   */
  statusMessage: string | null;
  /**
   * Raw ISDS dmMessageStatus code
   * @nullable
   */
  rawStateCode: number | null;
  /** When the message was sent (ISO 8601) */
  sentAt: string;
  /**
   * When the message was legally served (doručeno) — ISDS dmAcceptanceTime (by login or fiction) (ISO 8601)
   * @nullable
   */
  deliveredAt: string | null;
  /**
   * When the message reached the data box (dodáno) — ISDS dmDeliveryTime (ISO 8601)
   * @nullable
   */
  servedAt: string | null;
  /** Live ISDS delivery event timeline */
  events: MessageStatusEventDto[];
}
