/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Derived lifecycle state
 */
export type MessageStatusResponseDtoState = typeof MessageStatusResponseDtoState[keyof typeof MessageStatusResponseDtoState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageStatusResponseDtoState = {
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  SERVED: 'SERVED',
  FAILED: 'FAILED',
  UNKNOWN: 'UNKNOWN',
} as const;
