/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceResponseDto } from './invoiceResponseDto';

export interface PaginatedInvoiceResponseDto {
  data: InvoiceResponseDto[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}
