/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface ParsedPartyDto {
  /** @nullable */
  name: string | null;
  /**
   * IČO
   * @nullable
   */
  ico: string | null;
  /**
   * DIČ
   * @nullable
   */
  dic: string | null;
  /** @nullable */
  street: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  psc: string | null;
  /**
   * ISO 3166-1 alpha-2, e.g. CZ
   * @nullable
   */
  country: string | null;
}
