/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type ParsedInvoiceType =
  (typeof ParsedInvoiceType)[keyof typeof ParsedInvoiceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParsedInvoiceType = {
  ISSUED: 'ISSUED',
  RECEIVED: 'RECEIVED',
} as const;
