/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface ParsedBankAccountDto {
  /**
   * Czech format 123456789/0100
   * @nullable
   */
  number: string | null;
  /** @nullable */
  iban: string | null;
  /** @nullable */
  swift: string | null;
}
