/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface ParsedInvoiceItemDto {
  name: string;
  quantity: number;
  /** @nullable */
  unit: string | null;
  /** Unit price without VAT */
  unitPrice: number;
  /**
   * VAT rate %
   * @nullable
   */
  vatRate: number | null;
}
