/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * How type was decided: the company's own IČO/DIČ on the document (MATCH), the model's guess (MODEL) or the RECEIVED default (DEFAULT)
 */
export type ParsedInvoiceTypeSource =
  (typeof ParsedInvoiceTypeSource)[keyof typeof ParsedInvoiceTypeSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParsedInvoiceTypeSource = {
  MATCH: 'MATCH',
  MODEL: 'MODEL',
  DEFAULT: 'DEFAULT',
} as const;
