/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { PaymentResponseDtoPaymentMethod } from './paymentResponseDtoPaymentMethod';

export interface PaymentResponseDto {
  id: string;
  invoiceId: string;
  paymentMethod: PaymentResponseDtoPaymentMethod;
  amount: string;
  currency?: string;
  paymentDate: string;
  reference?: string;
  note?: string;
  exchangeRate?: string;
}
