/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface ReceiptParseDataDto {
  /** @nullable */
  vendor: string | null;
  /** @nullable */
  total: number | null;
  /** @nullable */
  vat: number | null;
  /** @nullable */
  currency: string | null;
  /** @nullable */
  date: string | null;
}
