/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface ReceiptLlmCallDto {
  attempt: number;
  durationMs: number;
  model: string;
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  validationErrors?: string[];
}
