/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * True if flagged unreliable (nespolehlivý plátce), false if reliable, null when not found.
 * @nullable
 */
export type RegistrationDataResponseDtoUnreliable = { [key: string]: unknown } | null;
