/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Date the payer was flagged unreliable (ISO date), if any.
 * @nullable
 */
export type RegistrationDataResponseDtoUnreliableSince = { [key: string]: unknown } | null;
