/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { SidloDto } from './sidloDto';
import type { AdresaDorucovaciDto } from './adresaDorucovaciDto';
import type { RegistrationDataResponseDtoUnreliable } from './registrationDataResponseDtoUnreliable';
import type { RegistrationDataResponseDtoUnreliableSince } from './registrationDataResponseDtoUnreliableSince';
import type { RegistrationDataResponseDtoTaxOfficeCode } from './registrationDataResponseDtoTaxOfficeCode';
import type { DphBankAccountDto } from './dphBankAccountDto';

export interface RegistrationDataResponseDto {
  ico: string;
  obchodniJmeno: string;
  jmeno?: string;
  prijmeni?: string;
  sidlo: SidloDto;
  pravniForma: string;
  financniUrad: string;
  datumVzniku: string;
  datumAktualizace: string;
  /** Looked-up DIČ, without the "CZ" prefix. */
  dic?: string;
  icoId: string;
  adresaDorucovaci: AdresaDorucovaciDto;
  /** False when the DIČ is not registered as a VAT payer. */
  found?: boolean;
  /**
   * True if flagged unreliable (nespolehlivý plátce), false if reliable, null when not found.
   * @nullable
   */
  unreliable?: RegistrationDataResponseDtoUnreliable;
  /**
   * Date the payer was flagged unreliable (ISO date), if any.
   * @nullable
   */
  unreliableSince?: RegistrationDataResponseDtoUnreliableSince;
  /**
   * Financial office code (číslo FÚ) the payer belongs to.
   * @nullable
   */
  taxOfficeCode?: RegistrationDataResponseDtoTaxOfficeCode;
  accounts?: DphBankAccountDto[];
  /** CRPDPH status code (0 = OK). */
  statusCode?: number;
  /** CRPDPH status text. */
  statusText?: string;
  /** When the registry generated the answer. */
  generatedAt?: string;
}
