/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Financial office code (číslo FÚ) the payer belongs to.
 * @nullable
 */
export type RegistrationDataResponseDtoTaxOfficeCode = { [key: string]: unknown } | null;
