/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { SelectedCompanyInputDtoKind } from './selectedCompanyInputDtoKind';
import type { EkonomickySubjektDto } from './ekonomickySubjektDto';

export interface SelectedCompanyInputDto {
  kind: SelectedCompanyInputDtoKind;
  /** Database company id */
  id?: string;
  /** Company ICO */
  ico?: string;
  /** Company name (for DB company) */
  name?: string;
  /** ARES business name */
  obchodniJmeno?: string;
  /** Short address text for ARES candidate */
  sidloText?: string;
  /** Company address for db_company item */
  address?: string;
  aresEntity?: EkonomickySubjektDto;
}
