/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type SelectedCompanyInputDtoKind = typeof SelectedCompanyInputDtoKind[keyof typeof SelectedCompanyInputDtoKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SelectedCompanyInputDtoKind = {
  db_company: 'db_company',
  ares_candidate: 'ares_candidate',
} as const;
