/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface SendMessageAttachmentDto {
  /** Attachment file name (becomes the ISDS dmFileDescr) */
  filename: string;
  /** Raw XML content of the attachment */
  content: string;
  /** MIME type of the attachment (defaults to text/xml) */
  mimeType?: string;
}
