/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { SendMessageAttachmentDto } from './sendMessageAttachmentDto';

export interface SendMessageDto {
  /** Recipient data box ID (dbIDRecipient — exactly 7 characters) */
  recipientId: string;
  /** Message subject (dmAnnotation, max 255 characters) */
  subject: string;
  /** XML files to attach — at least one; the first becomes "main" */
  attachments: SendMessageAttachmentDto[];
}
