/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { ContactResponseDto } from './contactResponseDto';

export interface SimpleInvoiceResponseDto {
  id: string;
  companyId: string;
  contactId?: string;
  number: string;
  createdDate: string;
  taxDate: string;
  total: number;
  totalTax: number;
  totalWithTax: number;
  description?: string;
  contact?: ContactResponseDto;
}
