/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface SubmitTaxResponseDto {
  /** Whether ISDS accepted and created the message */
  success: boolean;
  /**
   * ISDS message ID (dmID) — null when the send failed
   * @nullable
   */
  messageId: string | null;
  /** ISDS dmStatusCode — "0000" means success */
  statusCode: string;
  /** Human-readable ISDS dmStatusMessage */
  statusMessage: string;
  /** ID of the submitted tax filing */
  taxFilingId: string;
  /** Tax filing status after the call — SUBMITTED on success, unchanged otherwise */
  taxFilingStatus: string;
}
