/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type TaxFilingDetailResponseDtoStatus = typeof TaxFilingDetailResponseDtoStatus[keyof typeof TaxFilingDetailResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaxFilingDetailResponseDtoStatus = {
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  FAILED: 'FAILED',
  SUBMITTED: 'SUBMITTED',
  CANCELLED: 'CANCELLED',
} as const;
