/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { TaxFilingInvoiceRefDtoRole } from './taxFilingInvoiceRefDtoRole';

export interface TaxFilingInvoiceRefDto {
  invoiceId: string;
  role: TaxFilingInvoiceRefDtoRole;
}
