/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface TaxFilingSummaryDto {
  outputVat: number;
  inputVat: number;
  payableVat: number;
  issuedInvoicesCount: number;
  receivedInvoicesCount: number;
}
