/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { TaxFilingDetailResponseDtoStatus } from './taxFilingDetailResponseDtoStatus';
import type { TaxFilingDetailResponseDtoSubmissionType } from './taxFilingDetailResponseDtoSubmissionType';
import type { TaxFilingDetailResponseDtoSummary } from './taxFilingDetailResponseDtoSummary';
import type { TaxFilingInvoiceDetailDto } from './taxFilingInvoiceDetailDto';

export interface TaxFilingDetailResponseDto {
  id: string;
  companyId: string;
  month: number;
  year: number;
  status: TaxFilingDetailResponseDtoStatus;
  submissionType: TaxFilingDetailResponseDtoSubmissionType;
  createDate: string;
  /** @nullable */
  submissionDate?: string | null;
  /** @nullable */
  summary?: TaxFilingDetailResponseDtoSummary;
  /** @nullable */
  errorMessage?: string | null;
  createdAt: string;
  updatedAt: string;
  invoices: TaxFilingInvoiceDetailDto[];
}
