/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type TaxFilingResponseDtoSubmissionType = typeof TaxFilingResponseDtoSubmissionType[keyof typeof TaxFilingResponseDtoSubmissionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaxFilingResponseDtoSubmissionType = {
  REGULAR: 'REGULAR',
  CORRECTIVE: 'CORRECTIVE',
  FOLLOWUP: 'FOLLOWUP',
} as const;
