/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type TaxFilingInvoiceRefDtoRole = typeof TaxFilingInvoiceRefDtoRole[keyof typeof TaxFilingInvoiceRefDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaxFilingInvoiceRefDtoRole = {
  ISSUED: 'ISSUED',
  RECEIVED: 'RECEIVED',
  SIMPLE: 'SIMPLE',
} as const;
