/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { TaxFilingInvoiceDetailDtoRole } from './taxFilingInvoiceDetailDtoRole';
import type { InvoiceResponseDto } from './invoiceResponseDto';

export interface TaxFilingInvoiceDetailDto {
  role: TaxFilingInvoiceDetailDtoRole;
  invoice: InvoiceResponseDto;
}
