/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type TaxFilingDetailResponseDtoSubmissionType = typeof TaxFilingDetailResponseDtoSubmissionType[keyof typeof TaxFilingDetailResponseDtoSubmissionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaxFilingDetailResponseDtoSubmissionType = {
  REGULAR: 'REGULAR',
  CORRECTIVE: 'CORRECTIVE',
  FOLLOWUP: 'FOLLOWUP',
} as const;
