/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type TaxFilingInvoiceDetailDtoRole = typeof TaxFilingInvoiceDetailDtoRole[keyof typeof TaxFilingInvoiceDetailDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaxFilingInvoiceDetailDtoRole = {
  ISSUED: 'ISSUED',
  RECEIVED: 'RECEIVED',
  SIMPLE: 'SIMPLE',
} as const;
