/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface TestLoginDto {
  /** ISDS username to test. Provide together with `password` to verify credentials before they are saved on the company; omit both to test the company's already-saved credentials. */
  username?: string;
  /** ISDS password to test. Must be provided together with `username`. */
  password?: string;
}
