/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { TestLoginResponseDtoOwner } from './testLoginResponseDtoOwner';

export interface TestLoginResponseDto {
  /** Whether ISDS accepted the configured credentials */
  success: boolean;
  /** ISDS dbStatusCode — "0000" means success */
  statusCode: string;
  /** Human-readable ISDS dbStatusMessage */
  statusMessage: string;
  /**
   * Owner of the data box that was logged into
   * @nullable
   */
  owner: TestLoginResponseDtoOwner;
}
