/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { IsdsOwnerDto } from './isdsOwnerDto';

/**
 * Owner of the data box that was logged into
 * @nullable
 */
export type TestLoginResponseDtoOwner = IsdsOwnerDto | null;
