/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserProfileDto {
  firstName?: string;
  lastName?: string;
  /** Tax identification number used for VAT filings */
  dic?: string;
  /** Phone number used in VAT filings */
  phone?: string;
  /** Contact email used in VAT filings */
  email?: string;
}
