/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { UpdatePaymentDtoPaymentMethod } from './updatePaymentDtoPaymentMethod';

export interface UpdatePaymentDto {
  /** UUID of the payment */
  id: string;
  /** UUID of the related invoice */
  invoiceId?: string;
  paymentMethod?: UpdatePaymentDtoPaymentMethod;
  amount?: string;
  currency?: string;
  paymentDate?: string;
  reference?: string;
  note?: string;
  exchangeRate?: string;
}
