/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * CLAIMED is reserved for the future tax-filing workflow and cannot be set via API.
 */
export type UpdateInvoiceDtoVatClaimStatus = typeof UpdateInvoiceDtoVatClaimStatus[keyof typeof UpdateInvoiceDtoVatClaimStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateInvoiceDtoVatClaimStatus = {
  PENDING: 'PENDING',
  SKIPPED: 'SKIPPED',
} as const;
