/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceBankAccountSnapshotDto } from './invoiceBankAccountSnapshotDto';
import type { UpdateInvoiceDtoType } from './updateInvoiceDtoType';
import type { UpdateInvoiceDtoVatMode } from './updateInvoiceDtoVatMode';
import type { UpdateInvoiceDtoStatus } from './updateInvoiceDtoStatus';
import type { InvoiceItemDto } from './invoiceItemDto';
import type { UpdateInvoiceDtoVatClaimType } from './updateInvoiceDtoVatClaimType';
import type { UpdateInvoiceDtoVatClaimStatus } from './updateInvoiceDtoVatClaimStatus';

export interface UpdateInvoiceDto {
  /** UUID of the invoice */
  id: string;
  bankId?: string;
  /** Direct bank-account snapshot (mutually exclusive with `bankId`). Setting this clears `bankId`. */
  bankSnapshot?: InvoiceBankAccountSnapshotDto;
  /** UUID of the external party (Contact) */
  contactId?: string;
  number?: string;
  currency?: string;
  type?: UpdateInvoiceDtoType;
  vatMode?: UpdateInvoiceDtoVatMode;
  status?: UpdateInvoiceDtoStatus;
  exchangeRate?: number;
  createdDate?: string;
  duzpDate?: string;
  dueDate?: string;
  /** Array of invoice items. Totals are recomputed server-side when provided. */
  items?: InvoiceItemDto[];
  variableSymbol?: string;
  specificSymbol?: string;
  konstantSymbol?: string;
  note?: string;
  internalNote?: string;
  originalNumber?: string;
  description?: string;
  /** Pre-computed base total (kind=SIMPLE only). */
  total?: number;
  /** Pre-computed VAT amount (kind=SIMPLE only). */
  totalTax?: number;
  /** Pre-computed total with VAT (kind=SIMPLE only). */
  totalWithTax?: number;
  vatClaimType?: UpdateInvoiceDtoVatClaimType;
  /** Required when vatClaimType=PARTIAL. Must be in (0,1]. Forced to 1 when vatClaimType=FULL. */
  vatClaimRatio?: number;
  /** First day of the month in which VAT is claimed (YYYY-MM-01). */
  vatClaimMonth?: string;
  /** CLAIMED is reserved for the future tax-filing workflow and cannot be set via API. */
  vatClaimStatus?: UpdateInvoiceDtoVatClaimStatus;
  vatClaimNote?: string;
}
