/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateSimpleInvoiceDto {
  id: string;
  companyId?: string;
  number?: string;
  createdDate?: string;
  taxDate?: string;
  total?: number;
  totalTax?: number;
  totalWithTax?: number;
  description?: string;
}
