/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

/**
 * Whether the input-VAT deduction should be claimed (PENDING) or not (SKIPPED).
 */
export type UpdateInvoiceDtoVatClaimStatus =
  (typeof UpdateInvoiceDtoVatClaimStatus)[keyof typeof UpdateInvoiceDtoVatClaimStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateInvoiceDtoVatClaimStatus = {
  PENDING: 'PENDING',
  SKIPPED: 'SKIPPED',
} as const;
