/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type UpdateUserCompanyRoleDtoRole = typeof UpdateUserCompanyRoleDtoRole[keyof typeof UpdateUserCompanyRoleDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserCompanyRoleDtoRole = {
  OWNER: 'OWNER',
  ACCOUNTANT: 'ACCOUNTANT',
  MEMBER: 'MEMBER',
} as const;
