/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { InvoiceBankAccountSnapshotDto } from './invoiceBankAccountSnapshotDto';
import type { UpdateInvoiceDtoType } from './updateInvoiceDtoType';
import type { UpdateInvoiceDtoVatMode } from './updateInvoiceDtoVatMode';
import type { UpdateInvoiceDtoStatus } from './updateInvoiceDtoStatus';
import type { InvoiceItemDto } from './invoiceItemDto';
import type { InvoiceVatClaimDto } from './invoiceVatClaimDto';

export interface UpdateInvoiceDto {
  /** UUID of the invoice */
  id: string;
  bankId?: string;
  /** Direct bank-account snapshot (mutually exclusive with `bankId`). Setting this clears `bankId`. */
  bankSnapshot?: InvoiceBankAccountSnapshotDto;
  /** UUID of the external party (Contact) */
  contactId?: string;
  number?: string;
  currency?: string;
  type?: UpdateInvoiceDtoType;
  vatMode?: UpdateInvoiceDtoVatMode;
  status?: UpdateInvoiceDtoStatus;
  exchangeRate?: number;
  createdDate?: string;
  duzpDate?: string;
  dueDate?: string;
  /** Array of invoice items. Totals are recomputed server-side when provided. */
  items?: InvoiceItemDto[];
  variableSymbol?: string;
  specificSymbol?: string;
  konstantSymbol?: string;
  note?: string;
  internalNote?: string;
  originalNumber?: string;
  description?: string;
  /** Pre-computed base total (kind=SIMPLE only). */
  total?: number;
  /** Pre-computed VAT amount (kind=SIMPLE only). */
  totalTax?: number;
  /** Pre-computed total with VAT (kind=SIMPLE only). */
  totalWithTax?: number;
  /** Optional VAT claim metadata. When omitted, claim is left untouched. When provided, an existing claim is updated; if none exists, one is created. */
  vatClaim?: InvoiceVatClaimDto;
}
