/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateInvoiceDtoType } from './updateInvoiceDtoType';
import type { UpdateInvoiceDtoStatus } from './updateInvoiceDtoStatus';
import type { InvoiceItemDto } from './invoiceItemDto';

export interface UpdateInvoiceDto {
  /** UUID of the invoice */
  id: string;
  companyId?: string;
  bankId?: string;
  number?: string;
  currency?: string;
  type?: UpdateInvoiceDtoType;
  status?: UpdateInvoiceDtoStatus;
  exchangeRate?: number;
  createdDate?: string;
  taxDate?: string;
  dueDate?: string;
  total?: number;
  totalTax?: number;
  totalWithTax?: number;
  /** Array of invoice items */
  items?: InvoiceItemDto[];
}
