/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type UpdateInvoiceStatusDtoStatus = typeof UpdateInvoiceStatusDtoStatus[keyof typeof UpdateInvoiceStatusDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateInvoiceStatusDtoStatus = {
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
} as const;
