/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type UpdateInvoiceDtoVatClaimType = typeof UpdateInvoiceDtoVatClaimType[keyof typeof UpdateInvoiceDtoVatClaimType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateInvoiceDtoVatClaimType = {
  FULL: 'FULL',
  PARTIAL: 'PARTIAL',
} as const;
