/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export type UpdateInvoiceDtoVatMode = typeof UpdateInvoiceDtoVatMode[keyof typeof UpdateInvoiceDtoVatMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateInvoiceDtoVatMode = {
  STANDARD: 'STANDARD',
  NON_VAT_PAYER: 'NON_VAT_PAYER',
  REVERSE_CHARGE: 'REVERSE_CHARGE',
} as const;
