/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import type { UserCompanyResponseDtoRole } from './userCompanyResponseDtoRole';
import type { UserCompanyUserSummaryDto } from './userCompanyUserSummaryDto';
import type { UserCompanyCompanySummaryDto } from './userCompanyCompanySummaryDto';

export interface UserCompanyResponseDto {
  id: string;
  userId: string;
  companyId: string;
  role: UserCompanyResponseDtoRole;
  createdAt: string;
  user?: UserCompanyUserSummaryDto;
  company?: UserCompanyCompanySummaryDto;
}
