/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface UserProfileResponseDto {
  id: string;
  firstName: string;
  lastName: string;
}
