/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */

export interface VatBreakdownItemDto {
  /** VAT rate percentage (e.g. 21) */
  rate: number;
  /**
   * Taxable base amount at this rate
   * @nullable
   */
  base: number | null;
  /**
   * VAT amount at this rate
   * @nullable
   */
  amount: number | null;
}
