/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateInvoiceDto,
  DashboardStatsResponseDto,
  GetByMonthDto,
  InvoiceListByUserParams,
  InvoiceResponseDto,
  PaginatedInvoiceResponseDto
} from '.././model';





/**
 * @summary Create invoice
 */
export const invoiceCreate = (
    createInvoiceDto: CreateInvoiceDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InvoiceResponseDto>> => {
    
    
    return axios.default.post(
      `/invoices`,
      createInvoiceDto,options
    );
  }



export const getInvoiceCreateMutationOptions = <TError = AxiosError<InvoiceResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invoiceCreate>>, TError,{data: CreateInvoiceDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof invoiceCreate>>, TError,{data: CreateInvoiceDto}, TContext> => {

const mutationKey = ['invoiceCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invoiceCreate>>, {data: CreateInvoiceDto}> = (props) => {
          const {data} = props ?? {};

          return  invoiceCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InvoiceCreateMutationResult = NonNullable<Awaited<ReturnType<typeof invoiceCreate>>>
    export type InvoiceCreateMutationBody = CreateInvoiceDto
    export type InvoiceCreateMutationError = AxiosError<InvoiceResponseDto>

    /**
 * @summary Create invoice
 */
export const useInvoiceCreate = <TError = AxiosError<InvoiceResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invoiceCreate>>, TError,{data: CreateInvoiceDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invoiceCreate>>,
        TError,
        {data: CreateInvoiceDto},
        TContext
      > => {

      const mutationOptions = getInvoiceCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List invoices by user with filtering and pagination
 */
export const invoiceListByUser = (
    params?: InvoiceListByUserParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedInvoiceResponseDto>> => {
    
    
    return axios.default.get(
      `/invoices/list`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getInvoiceListByUserQueryKey = (params?: InvoiceListByUserParams,) => {
    return [
    `/invoices/list`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getInvoiceListByUserQueryOptions = <TData = Awaited<ReturnType<typeof invoiceListByUser>>, TError = AxiosError<PaginatedInvoiceResponseDto>>(params?: InvoiceListByUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceListByUser>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInvoiceListByUserQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceListByUser>>> = ({ signal }) => invoiceListByUser(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof invoiceListByUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InvoiceListByUserQueryResult = NonNullable<Awaited<ReturnType<typeof invoiceListByUser>>>
export type InvoiceListByUserQueryError = AxiosError<PaginatedInvoiceResponseDto>


export function useInvoiceListByUser<TData = Awaited<ReturnType<typeof invoiceListByUser>>, TError = AxiosError<PaginatedInvoiceResponseDto>>(
 params: undefined |  InvoiceListByUserParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceListByUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceListByUser>>,
          TError,
          Awaited<ReturnType<typeof invoiceListByUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceListByUser<TData = Awaited<ReturnType<typeof invoiceListByUser>>, TError = AxiosError<PaginatedInvoiceResponseDto>>(
 params?: InvoiceListByUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceListByUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceListByUser>>,
          TError,
          Awaited<ReturnType<typeof invoiceListByUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceListByUser<TData = Awaited<ReturnType<typeof invoiceListByUser>>, TError = AxiosError<PaginatedInvoiceResponseDto>>(
 params?: InvoiceListByUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceListByUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List invoices by user with filtering and pagination
 */

export function useInvoiceListByUser<TData = Awaited<ReturnType<typeof invoiceListByUser>>, TError = AxiosError<PaginatedInvoiceResponseDto>>(
 params?: InvoiceListByUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceListByUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInvoiceListByUserQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of invoices for current user in current year
 */
export const invoiceGetCount = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<number>> => {
    
    
    return axios.default.get(
      `/invoices/count`,options
    );
  }




export const getInvoiceGetCountQueryKey = () => {
    return [
    `/invoices/count`
    ] as const;
    }

    
export const getInvoiceGetCountQueryOptions = <TData = Awaited<ReturnType<typeof invoiceGetCount>>, TError = AxiosError<number>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetCount>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInvoiceGetCountQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceGetCount>>> = ({ signal }) => invoiceGetCount({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof invoiceGetCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InvoiceGetCountQueryResult = NonNullable<Awaited<ReturnType<typeof invoiceGetCount>>>
export type InvoiceGetCountQueryError = AxiosError<number>


export function useInvoiceGetCount<TData = Awaited<ReturnType<typeof invoiceGetCount>>, TError = AxiosError<number>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceGetCount>>,
          TError,
          Awaited<ReturnType<typeof invoiceGetCount>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceGetCount<TData = Awaited<ReturnType<typeof invoiceGetCount>>, TError = AxiosError<number>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceGetCount>>,
          TError,
          Awaited<ReturnType<typeof invoiceGetCount>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceGetCount<TData = Awaited<ReturnType<typeof invoiceGetCount>>, TError = AxiosError<number>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetCount>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get count of invoices for current user in current year
 */

export function useInvoiceGetCount<TData = Awaited<ReturnType<typeof invoiceGetCount>>, TError = AxiosError<number>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetCount>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInvoiceGetCountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get dashboard stats
 */
export const invoiceGetStats = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DashboardStatsResponseDto>> => {
    
    
    return axios.default.get(
      `/invoices/stats`,options
    );
  }




export const getInvoiceGetStatsQueryKey = () => {
    return [
    `/invoices/stats`
    ] as const;
    }

    
export const getInvoiceGetStatsQueryOptions = <TData = Awaited<ReturnType<typeof invoiceGetStats>>, TError = AxiosError<DashboardStatsResponseDto>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetStats>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInvoiceGetStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceGetStats>>> = ({ signal }) => invoiceGetStats({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof invoiceGetStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InvoiceGetStatsQueryResult = NonNullable<Awaited<ReturnType<typeof invoiceGetStats>>>
export type InvoiceGetStatsQueryError = AxiosError<DashboardStatsResponseDto>


export function useInvoiceGetStats<TData = Awaited<ReturnType<typeof invoiceGetStats>>, TError = AxiosError<DashboardStatsResponseDto>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceGetStats>>,
          TError,
          Awaited<ReturnType<typeof invoiceGetStats>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceGetStats<TData = Awaited<ReturnType<typeof invoiceGetStats>>, TError = AxiosError<DashboardStatsResponseDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceGetStats>>,
          TError,
          Awaited<ReturnType<typeof invoiceGetStats>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceGetStats<TData = Awaited<ReturnType<typeof invoiceGetStats>>, TError = AxiosError<DashboardStatsResponseDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetStats>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get dashboard stats
 */

export function useInvoiceGetStats<TData = Awaited<ReturnType<typeof invoiceGetStats>>, TError = AxiosError<DashboardStatsResponseDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetStats>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInvoiceGetStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get invoice by id
 */
export const invoiceGet = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InvoiceResponseDto>> => {
    
    
    return axios.default.get(
      `/invoices/${id}`,options
    );
  }




export const getInvoiceGetQueryKey = (id?: string,) => {
    return [
    `/invoices/${id}`
    ] as const;
    }

    
export const getInvoiceGetQueryOptions = <TData = Awaited<ReturnType<typeof invoiceGet>>, TError = AxiosError<InvoiceResponseDto>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInvoiceGetQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceGet>>> = ({ signal }) => invoiceGet(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof invoiceGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InvoiceGetQueryResult = NonNullable<Awaited<ReturnType<typeof invoiceGet>>>
export type InvoiceGetQueryError = AxiosError<InvoiceResponseDto>


export function useInvoiceGet<TData = Awaited<ReturnType<typeof invoiceGet>>, TError = AxiosError<InvoiceResponseDto>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceGet>>,
          TError,
          Awaited<ReturnType<typeof invoiceGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceGet<TData = Awaited<ReturnType<typeof invoiceGet>>, TError = AxiosError<InvoiceResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceGet>>,
          TError,
          Awaited<ReturnType<typeof invoiceGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceGet<TData = Awaited<ReturnType<typeof invoiceGet>>, TError = AxiosError<InvoiceResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get invoice by id
 */

export function useInvoiceGet<TData = Awaited<ReturnType<typeof invoiceGet>>, TError = AxiosError<InvoiceResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInvoiceGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get invoices by month and year
 */
export const invoiceGetByMonth = (
    getByMonthDto: GetByMonthDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InvoiceResponseDto[]>> => {
    
    
    return axios.default.post(
      `/invoices/byMonth`,
      getByMonthDto,options
    );
  }



export const getInvoiceGetByMonthMutationOptions = <TError = AxiosError<InvoiceResponseDto[]>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invoiceGetByMonth>>, TError,{data: GetByMonthDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof invoiceGetByMonth>>, TError,{data: GetByMonthDto}, TContext> => {

const mutationKey = ['invoiceGetByMonth'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invoiceGetByMonth>>, {data: GetByMonthDto}> = (props) => {
          const {data} = props ?? {};

          return  invoiceGetByMonth(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InvoiceGetByMonthMutationResult = NonNullable<Awaited<ReturnType<typeof invoiceGetByMonth>>>
    export type InvoiceGetByMonthMutationBody = GetByMonthDto
    export type InvoiceGetByMonthMutationError = AxiosError<InvoiceResponseDto[]>

    /**
 * @summary Get invoices by month and year
 */
export const useInvoiceGetByMonth = <TError = AxiosError<InvoiceResponseDto[]>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invoiceGetByMonth>>, TError,{data: GetByMonthDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invoiceGetByMonth>>,
        TError,
        {data: GetByMonthDto},
        TContext
      > => {

      const mutationOptions = getInvoiceGetByMonthMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get invoice by number
 */
export const invoiceGetByNumber = (
    number: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InvoiceResponseDto>> => {
    
    
    return axios.default.get(
      `/invoices/byNumber/${number}`,options
    );
  }




export const getInvoiceGetByNumberQueryKey = (number?: string,) => {
    return [
    `/invoices/byNumber/${number}`
    ] as const;
    }

    
export const getInvoiceGetByNumberQueryOptions = <TData = Awaited<ReturnType<typeof invoiceGetByNumber>>, TError = AxiosError<InvoiceResponseDto>>(number: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetByNumber>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInvoiceGetByNumberQueryKey(number);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceGetByNumber>>> = ({ signal }) => invoiceGetByNumber(number, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(number), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof invoiceGetByNumber>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InvoiceGetByNumberQueryResult = NonNullable<Awaited<ReturnType<typeof invoiceGetByNumber>>>
export type InvoiceGetByNumberQueryError = AxiosError<InvoiceResponseDto>


export function useInvoiceGetByNumber<TData = Awaited<ReturnType<typeof invoiceGetByNumber>>, TError = AxiosError<InvoiceResponseDto>>(
 number: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetByNumber>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceGetByNumber>>,
          TError,
          Awaited<ReturnType<typeof invoiceGetByNumber>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceGetByNumber<TData = Awaited<ReturnType<typeof invoiceGetByNumber>>, TError = AxiosError<InvoiceResponseDto>>(
 number: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetByNumber>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceGetByNumber>>,
          TError,
          Awaited<ReturnType<typeof invoiceGetByNumber>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoiceGetByNumber<TData = Awaited<ReturnType<typeof invoiceGetByNumber>>, TError = AxiosError<InvoiceResponseDto>>(
 number: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetByNumber>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get invoice by number
 */

export function useInvoiceGetByNumber<TData = Awaited<ReturnType<typeof invoiceGetByNumber>>, TError = AxiosError<InvoiceResponseDto>>(
 number: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoiceGetByNumber>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInvoiceGetByNumberQueryOptions(number,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



