/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateSimpleInvoiceDto,
  SimpleInvoiceResponseDto,
  UpdateSimpleInvoiceDto
} from '.././model';





/**
 * @summary Create simple invoice
 */
export const simpleInvoiceCreate = (
    createSimpleInvoiceDto: CreateSimpleInvoiceDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SimpleInvoiceResponseDto>> => {
    
    
    return axios.default.post(
      `/simple-invoices`,
      createSimpleInvoiceDto,options
    );
  }



export const getSimpleInvoiceCreateMutationOptions = <TError = AxiosError<SimpleInvoiceResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simpleInvoiceCreate>>, TError,{data: CreateSimpleInvoiceDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof simpleInvoiceCreate>>, TError,{data: CreateSimpleInvoiceDto}, TContext> => {

const mutationKey = ['simpleInvoiceCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof simpleInvoiceCreate>>, {data: CreateSimpleInvoiceDto}> = (props) => {
          const {data} = props ?? {};

          return  simpleInvoiceCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SimpleInvoiceCreateMutationResult = NonNullable<Awaited<ReturnType<typeof simpleInvoiceCreate>>>
    export type SimpleInvoiceCreateMutationBody = CreateSimpleInvoiceDto
    export type SimpleInvoiceCreateMutationError = AxiosError<SimpleInvoiceResponseDto>

    /**
 * @summary Create simple invoice
 */
export const useSimpleInvoiceCreate = <TError = AxiosError<SimpleInvoiceResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simpleInvoiceCreate>>, TError,{data: CreateSimpleInvoiceDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof simpleInvoiceCreate>>,
        TError,
        {data: CreateSimpleInvoiceDto},
        TContext
      > => {

      const mutationOptions = getSimpleInvoiceCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update simple invoice
 */
export const simpleInvoiceUpdate = (
    updateSimpleInvoiceDto: UpdateSimpleInvoiceDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SimpleInvoiceResponseDto>> => {
    
    
    return axios.default.patch(
      `/simple-invoices`,
      updateSimpleInvoiceDto,options
    );
  }



export const getSimpleInvoiceUpdateMutationOptions = <TError = AxiosError<SimpleInvoiceResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simpleInvoiceUpdate>>, TError,{data: UpdateSimpleInvoiceDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof simpleInvoiceUpdate>>, TError,{data: UpdateSimpleInvoiceDto}, TContext> => {

const mutationKey = ['simpleInvoiceUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof simpleInvoiceUpdate>>, {data: UpdateSimpleInvoiceDto}> = (props) => {
          const {data} = props ?? {};

          return  simpleInvoiceUpdate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SimpleInvoiceUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof simpleInvoiceUpdate>>>
    export type SimpleInvoiceUpdateMutationBody = UpdateSimpleInvoiceDto
    export type SimpleInvoiceUpdateMutationError = AxiosError<SimpleInvoiceResponseDto>

    /**
 * @summary Update simple invoice
 */
export const useSimpleInvoiceUpdate = <TError = AxiosError<SimpleInvoiceResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simpleInvoiceUpdate>>, TError,{data: UpdateSimpleInvoiceDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof simpleInvoiceUpdate>>,
        TError,
        {data: UpdateSimpleInvoiceDto},
        TContext
      > => {

      const mutationOptions = getSimpleInvoiceUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List simple invoices by user
 */
export const simpleInvoiceListByUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SimpleInvoiceResponseDto[]>> => {
    
    
    return axios.default.get(
      `/simple-invoices/list`,options
    );
  }




export const getSimpleInvoiceListByUserQueryKey = () => {
    return [
    `/simple-invoices/list`
    ] as const;
    }

    
export const getSimpleInvoiceListByUserQueryOptions = <TData = Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError = AxiosError<SimpleInvoiceResponseDto[]>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSimpleInvoiceListByUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof simpleInvoiceListByUser>>> = ({ signal }) => simpleInvoiceListByUser({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SimpleInvoiceListByUserQueryResult = NonNullable<Awaited<ReturnType<typeof simpleInvoiceListByUser>>>
export type SimpleInvoiceListByUserQueryError = AxiosError<SimpleInvoiceResponseDto[]>


export function useSimpleInvoiceListByUser<TData = Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError = AxiosError<SimpleInvoiceResponseDto[]>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof simpleInvoiceListByUser>>,
          TError,
          Awaited<ReturnType<typeof simpleInvoiceListByUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSimpleInvoiceListByUser<TData = Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError = AxiosError<SimpleInvoiceResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof simpleInvoiceListByUser>>,
          TError,
          Awaited<ReturnType<typeof simpleInvoiceListByUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSimpleInvoiceListByUser<TData = Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError = AxiosError<SimpleInvoiceResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List simple invoices by user
 */

export function useSimpleInvoiceListByUser<TData = Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError = AxiosError<SimpleInvoiceResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceListByUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSimpleInvoiceListByUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get simple invoice by id
 */
export const simpleInvoiceGet = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SimpleInvoiceResponseDto>> => {
    
    
    return axios.default.get(
      `/simple-invoices/${id}`,options
    );
  }




export const getSimpleInvoiceGetQueryKey = (id?: string,) => {
    return [
    `/simple-invoices/${id}`
    ] as const;
    }

    
export const getSimpleInvoiceGetQueryOptions = <TData = Awaited<ReturnType<typeof simpleInvoiceGet>>, TError = AxiosError<SimpleInvoiceResponseDto>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSimpleInvoiceGetQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof simpleInvoiceGet>>> = ({ signal }) => simpleInvoiceGet(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SimpleInvoiceGetQueryResult = NonNullable<Awaited<ReturnType<typeof simpleInvoiceGet>>>
export type SimpleInvoiceGetQueryError = AxiosError<SimpleInvoiceResponseDto>


export function useSimpleInvoiceGet<TData = Awaited<ReturnType<typeof simpleInvoiceGet>>, TError = AxiosError<SimpleInvoiceResponseDto>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof simpleInvoiceGet>>,
          TError,
          Awaited<ReturnType<typeof simpleInvoiceGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSimpleInvoiceGet<TData = Awaited<ReturnType<typeof simpleInvoiceGet>>, TError = AxiosError<SimpleInvoiceResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof simpleInvoiceGet>>,
          TError,
          Awaited<ReturnType<typeof simpleInvoiceGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSimpleInvoiceGet<TData = Awaited<ReturnType<typeof simpleInvoiceGet>>, TError = AxiosError<SimpleInvoiceResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get simple invoice by id
 */

export function useSimpleInvoiceGet<TData = Awaited<ReturnType<typeof simpleInvoiceGet>>, TError = AxiosError<SimpleInvoiceResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof simpleInvoiceGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSimpleInvoiceGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete simple invoice
 */
export const simpleInvoiceDelete = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/simple-invoices/${id}`,options
    );
  }



export const getSimpleInvoiceDeleteMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simpleInvoiceDelete>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof simpleInvoiceDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['simpleInvoiceDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof simpleInvoiceDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  simpleInvoiceDelete(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SimpleInvoiceDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof simpleInvoiceDelete>>>
    
    export type SimpleInvoiceDeleteMutationError = AxiosError<unknown>

    /**
 * @summary Delete simple invoice
 */
export const useSimpleInvoiceDelete = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simpleInvoiceDelete>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof simpleInvoiceDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getSimpleInvoiceDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    