/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUserProfileDto,
  UpdateUserProfileDto,
  UserProfileResponseDto
} from '.././model';





/**
 * @summary Create user profile
 */
export const userProfileCreate = (
    createUserProfileDto: CreateUserProfileDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserProfileResponseDto>> => {
    
    
    return axios.default.post(
      `/user-profile`,
      createUserProfileDto,options
    );
  }



export const getUserProfileCreateMutationOptions = <TError = AxiosError<UserProfileResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userProfileCreate>>, TError,{data: CreateUserProfileDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userProfileCreate>>, TError,{data: CreateUserProfileDto}, TContext> => {

const mutationKey = ['userProfileCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userProfileCreate>>, {data: CreateUserProfileDto}> = (props) => {
          const {data} = props ?? {};

          return  userProfileCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserProfileCreateMutationResult = NonNullable<Awaited<ReturnType<typeof userProfileCreate>>>
    export type UserProfileCreateMutationBody = CreateUserProfileDto
    export type UserProfileCreateMutationError = AxiosError<UserProfileResponseDto>

    /**
 * @summary Create user profile
 */
export const useUserProfileCreate = <TError = AxiosError<UserProfileResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userProfileCreate>>, TError,{data: CreateUserProfileDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userProfileCreate>>,
        TError,
        {data: CreateUserProfileDto},
        TContext
      > => {

      const mutationOptions = getUserProfileCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get user profile
 */
export const userProfileGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserProfileResponseDto>> => {
    
    
    return axios.default.get(
      `/user-profile`,options
    );
  }




export const getUserProfileGetQueryKey = () => {
    return [
    `/user-profile`
    ] as const;
    }

    
export const getUserProfileGetQueryOptions = <TData = Awaited<ReturnType<typeof userProfileGet>>, TError = AxiosError<UserProfileResponseDto>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfileGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserProfileGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userProfileGet>>> = ({ signal }) => userProfileGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userProfileGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserProfileGetQueryResult = NonNullable<Awaited<ReturnType<typeof userProfileGet>>>
export type UserProfileGetQueryError = AxiosError<UserProfileResponseDto>


export function useUserProfileGet<TData = Awaited<ReturnType<typeof userProfileGet>>, TError = AxiosError<UserProfileResponseDto>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfileGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userProfileGet>>,
          TError,
          Awaited<ReturnType<typeof userProfileGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserProfileGet<TData = Awaited<ReturnType<typeof userProfileGet>>, TError = AxiosError<UserProfileResponseDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfileGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userProfileGet>>,
          TError,
          Awaited<ReturnType<typeof userProfileGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserProfileGet<TData = Awaited<ReturnType<typeof userProfileGet>>, TError = AxiosError<UserProfileResponseDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfileGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user profile
 */

export function useUserProfileGet<TData = Awaited<ReturnType<typeof userProfileGet>>, TError = AxiosError<UserProfileResponseDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfileGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserProfileGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update user profile
 */
export const userProfileUpdate = (
    updateUserProfileDto: UpdateUserProfileDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserProfileResponseDto>> => {
    
    
    return axios.default.patch(
      `/user-profile`,
      updateUserProfileDto,options
    );
  }



export const getUserProfileUpdateMutationOptions = <TError = AxiosError<UserProfileResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userProfileUpdate>>, TError,{data: UpdateUserProfileDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userProfileUpdate>>, TError,{data: UpdateUserProfileDto}, TContext> => {

const mutationKey = ['userProfileUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userProfileUpdate>>, {data: UpdateUserProfileDto}> = (props) => {
          const {data} = props ?? {};

          return  userProfileUpdate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserProfileUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof userProfileUpdate>>>
    export type UserProfileUpdateMutationBody = UpdateUserProfileDto
    export type UserProfileUpdateMutationError = AxiosError<UserProfileResponseDto>

    /**
 * @summary Update user profile
 */
export const useUserProfileUpdate = <TError = AxiosError<UserProfileResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userProfileUpdate>>, TError,{data: UpdateUserProfileDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userProfileUpdate>>,
        TError,
        {data: UpdateUserProfileDto},
        TContext
      > => {

      const mutationOptions = getUserProfileUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    