/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ContactResponseDto,
  CreateContactDto,
  FindContactsByNameParams,
  UpdateContactDto
} from '.././model';





/**
 * @summary Create contact
 */
export const createContact = (
    createContactDto: CreateContactDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ContactResponseDto>> => {
    
    
    return axios.default.post(
      `/contacts`,
      createContactDto,options
    );
  }



export const getCreateContactMutationOptions = <TError = AxiosError<ContactResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContact>>, TError,{data: CreateContactDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createContact>>, TError,{data: CreateContactDto}, TContext> => {

const mutationKey = ['createContact'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createContact>>, {data: CreateContactDto}> = (props) => {
          const {data} = props ?? {};

          return  createContact(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateContactMutationResult = NonNullable<Awaited<ReturnType<typeof createContact>>>
    export type CreateContactMutationBody = CreateContactDto
    export type CreateContactMutationError = AxiosError<ContactResponseDto>

    /**
 * @summary Create contact
 */
export const useCreateContact = <TError = AxiosError<ContactResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContact>>, TError,{data: CreateContactDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createContact>>,
        TError,
        {data: CreateContactDto},
        TContext
      > => {

      const mutationOptions = getCreateContactMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update contact
 */
export const updateContact = (
    updateContactDto: UpdateContactDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ContactResponseDto>> => {
    
    
    return axios.default.put(
      `/contacts`,
      updateContactDto,options
    );
  }



export const getUpdateContactMutationOptions = <TError = AxiosError<ContactResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContact>>, TError,{data: UpdateContactDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateContact>>, TError,{data: UpdateContactDto}, TContext> => {

const mutationKey = ['updateContact'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateContact>>, {data: UpdateContactDto}> = (props) => {
          const {data} = props ?? {};

          return  updateContact(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateContactMutationResult = NonNullable<Awaited<ReturnType<typeof updateContact>>>
    export type UpdateContactMutationBody = UpdateContactDto
    export type UpdateContactMutationError = AxiosError<ContactResponseDto>

    /**
 * @summary Update contact
 */
export const useUpdateContact = <TError = AxiosError<ContactResponseDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContact>>, TError,{data: UpdateContactDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateContact>>,
        TError,
        {data: UpdateContactDto},
        TContext
      > => {

      const mutationOptions = getUpdateContactMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List contacts
 */
export const listContacts = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ContactResponseDto[]>> => {
    
    
    return axios.default.get(
      `/contacts`,options
    );
  }




export const getListContactsQueryKey = () => {
    return [
    `/contacts`
    ] as const;
    }

    
export const getListContactsQueryOptions = <TData = Awaited<ReturnType<typeof listContacts>>, TError = AxiosError<ContactResponseDto[]>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContacts>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListContactsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listContacts>>> = ({ signal }) => listContacts({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listContacts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListContactsQueryResult = NonNullable<Awaited<ReturnType<typeof listContacts>>>
export type ListContactsQueryError = AxiosError<ContactResponseDto[]>


export function useListContacts<TData = Awaited<ReturnType<typeof listContacts>>, TError = AxiosError<ContactResponseDto[]>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContacts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listContacts>>,
          TError,
          Awaited<ReturnType<typeof listContacts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListContacts<TData = Awaited<ReturnType<typeof listContacts>>, TError = AxiosError<ContactResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContacts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listContacts>>,
          TError,
          Awaited<ReturnType<typeof listContacts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListContacts<TData = Awaited<ReturnType<typeof listContacts>>, TError = AxiosError<ContactResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContacts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List contacts
 */

export function useListContacts<TData = Awaited<ReturnType<typeof listContacts>>, TError = AxiosError<ContactResponseDto[]>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContacts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListContactsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Find contacts by name
 */
export const findContactsByName = (
    params: FindContactsByNameParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ContactResponseDto[]>> => {
    
    
    return axios.default.get(
      `/contacts/search/by-name`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getFindContactsByNameQueryKey = (params?: FindContactsByNameParams,) => {
    return [
    `/contacts/search/by-name`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFindContactsByNameQueryOptions = <TData = Awaited<ReturnType<typeof findContactsByName>>, TError = AxiosError<ContactResponseDto[]>>(params: FindContactsByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findContactsByName>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindContactsByNameQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findContactsByName>>> = ({ signal }) => findContactsByName(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findContactsByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindContactsByNameQueryResult = NonNullable<Awaited<ReturnType<typeof findContactsByName>>>
export type FindContactsByNameQueryError = AxiosError<ContactResponseDto[]>


export function useFindContactsByName<TData = Awaited<ReturnType<typeof findContactsByName>>, TError = AxiosError<ContactResponseDto[]>>(
 params: FindContactsByNameParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findContactsByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findContactsByName>>,
          TError,
          Awaited<ReturnType<typeof findContactsByName>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindContactsByName<TData = Awaited<ReturnType<typeof findContactsByName>>, TError = AxiosError<ContactResponseDto[]>>(
 params: FindContactsByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findContactsByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findContactsByName>>,
          TError,
          Awaited<ReturnType<typeof findContactsByName>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindContactsByName<TData = Awaited<ReturnType<typeof findContactsByName>>, TError = AxiosError<ContactResponseDto[]>>(
 params: FindContactsByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findContactsByName>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Find contacts by name
 */

export function useFindContactsByName<TData = Awaited<ReturnType<typeof findContactsByName>>, TError = AxiosError<ContactResponseDto[]>>(
 params: FindContactsByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findContactsByName>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindContactsByNameQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get contact
 */
export const getContact = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ContactResponseDto>> => {
    
    
    return axios.default.get(
      `/contacts/${id}`,options
    );
  }




export const getGetContactQueryKey = (id?: string,) => {
    return [
    `/contacts/${id}`
    ] as const;
    }

    
export const getGetContactQueryOptions = <TData = Awaited<ReturnType<typeof getContact>>, TError = AxiosError<ContactResponseDto>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContact>>> = ({ signal }) => getContact(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactQueryResult = NonNullable<Awaited<ReturnType<typeof getContact>>>
export type GetContactQueryError = AxiosError<ContactResponseDto>


export function useGetContact<TData = Awaited<ReturnType<typeof getContact>>, TError = AxiosError<ContactResponseDto>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContact>>,
          TError,
          Awaited<ReturnType<typeof getContact>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContact<TData = Awaited<ReturnType<typeof getContact>>, TError = AxiosError<ContactResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContact>>,
          TError,
          Awaited<ReturnType<typeof getContact>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContact<TData = Awaited<ReturnType<typeof getContact>>, TError = AxiosError<ContactResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get contact
 */

export function useGetContact<TData = Awaited<ReturnType<typeof getContact>>, TError = AxiosError<ContactResponseDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete contact
 */
export const deleteContact = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/contacts/${id}`,options
    );
  }



export const getDeleteContactMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteContact'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContact>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteContact(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteContactMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContact>>>
    
    export type DeleteContactMutationError = AxiosError<unknown>

    /**
 * @summary Delete contact
 */
export const useDeleteContact = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteContact>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteContactMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    