/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * accounting
 * Accounting API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DataMessageDto,
  MessageStatusResponseDto,
  SendMessageDto,
  SendMessageResponseDto,
  SubmitTaxResponseDto,
  TestLoginDto,
  TestLoginResponseDto
} from '.././model';





/**
 * @summary Test the ISDS (datové schránky) connection by logging in via SOAP. Pass username + password to verify credentials before saving them; send an empty body to test the company's saved credentials.
 */
export const dataMessagesTestLogin = (
    testLoginDto: TestLoginDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TestLoginResponseDto>> => {
    
    
    return axios.default.post(
      `/data-messages/test-login`,
      testLoginDto,options
    );
  }



export const getDataMessagesTestLoginMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataMessagesTestLogin>>, TError,{data: TestLoginDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof dataMessagesTestLogin>>, TError,{data: TestLoginDto}, TContext> => {

const mutationKey = ['dataMessagesTestLogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dataMessagesTestLogin>>, {data: TestLoginDto}> = (props) => {
          const {data} = props ?? {};

          return  dataMessagesTestLogin(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DataMessagesTestLoginMutationResult = NonNullable<Awaited<ReturnType<typeof dataMessagesTestLogin>>>
    export type DataMessagesTestLoginMutationBody = TestLoginDto
    export type DataMessagesTestLoginMutationError = AxiosError<unknown>

    /**
 * @summary Test the ISDS (datové schránky) connection by logging in via SOAP. Pass username + password to verify credentials before saving them; send an empty body to test the company's saved credentials.
 */
export const useDataMessagesTestLogin = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataMessagesTestLogin>>, TError,{data: TestLoginDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dataMessagesTestLogin>>,
        TError,
        {data: TestLoginDto},
        TContext
      > => {

      const mutationOptions = getDataMessagesTestLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Send a data message with XML attachments via ISDS
 */
export const dataMessagesSend = (
    sendMessageDto: SendMessageDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SendMessageResponseDto>> => {
    
    
    return axios.default.post(
      `/data-messages/send`,
      sendMessageDto,options
    );
  }



export const getDataMessagesSendMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataMessagesSend>>, TError,{data: SendMessageDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof dataMessagesSend>>, TError,{data: SendMessageDto}, TContext> => {

const mutationKey = ['dataMessagesSend'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dataMessagesSend>>, {data: SendMessageDto}> = (props) => {
          const {data} = props ?? {};

          return  dataMessagesSend(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DataMessagesSendMutationResult = NonNullable<Awaited<ReturnType<typeof dataMessagesSend>>>
    export type DataMessagesSendMutationBody = SendMessageDto
    export type DataMessagesSendMutationError = AxiosError<unknown>

    /**
 * @summary Send a data message with XML attachments via ISDS
 */
export const useDataMessagesSend = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataMessagesSend>>, TError,{data: SendMessageDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dataMessagesSend>>,
        TError,
        {data: SendMessageDto},
        TContext
      > => {

      const mutationOptions = getDataMessagesSendMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List data messages recorded for the current company
 */
export const dataMessagesList = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DataMessageDto[]>> => {
    
    
    return axios.default.get(
      `/data-messages/messages`,options
    );
  }




export const getDataMessagesListQueryKey = () => {
    return [
    `/data-messages/messages`
    ] as const;
    }

    
export const getDataMessagesListQueryOptions = <TData = Awaited<ReturnType<typeof dataMessagesList>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDataMessagesListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dataMessagesList>>> = ({ signal }) => dataMessagesList({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dataMessagesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DataMessagesListQueryResult = NonNullable<Awaited<ReturnType<typeof dataMessagesList>>>
export type DataMessagesListQueryError = AxiosError<unknown>


export function useDataMessagesList<TData = Awaited<ReturnType<typeof dataMessagesList>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dataMessagesList>>,
          TError,
          Awaited<ReturnType<typeof dataMessagesList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataMessagesList<TData = Awaited<ReturnType<typeof dataMessagesList>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dataMessagesList>>,
          TError,
          Awaited<ReturnType<typeof dataMessagesList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataMessagesList<TData = Awaited<ReturnType<typeof dataMessagesList>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List data messages recorded for the current company
 */

export function useDataMessagesList<TData = Awaited<ReturnType<typeof dataMessagesList>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDataMessagesListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Submit a tax filing (DPH + KH XML) to the financial office via ISDS
 */
export const dataMessagesSubmitTax = (
    taxFilingId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubmitTaxResponseDto>> => {
    
    
    return axios.default.post(
      `/data-messages/submit-tax/${taxFilingId}`,undefined,options
    );
  }



export const getDataMessagesSubmitTaxMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataMessagesSubmitTax>>, TError,{taxFilingId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof dataMessagesSubmitTax>>, TError,{taxFilingId: string}, TContext> => {

const mutationKey = ['dataMessagesSubmitTax'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dataMessagesSubmitTax>>, {taxFilingId: string}> = (props) => {
          const {taxFilingId} = props ?? {};

          return  dataMessagesSubmitTax(taxFilingId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DataMessagesSubmitTaxMutationResult = NonNullable<Awaited<ReturnType<typeof dataMessagesSubmitTax>>>
    
    export type DataMessagesSubmitTaxMutationError = AxiosError<unknown>

    /**
 * @summary Submit a tax filing (DPH + KH XML) to the financial office via ISDS
 */
export const useDataMessagesSubmitTax = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataMessagesSubmitTax>>, TError,{taxFilingId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dataMessagesSubmitTax>>,
        TError,
        {taxFilingId: string},
        TContext
      > => {

      const mutationOptions = getDataMessagesSubmitTaxMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get the ISDS delivery status of a recorded data message
 */
export const dataMessagesGetStatus = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MessageStatusResponseDto>> => {
    
    
    return axios.default.get(
      `/data-messages/messages/${id}/status`,options
    );
  }




export const getDataMessagesGetStatusQueryKey = (id?: string,) => {
    return [
    `/data-messages/messages/${id}/status`
    ] as const;
    }

    
export const getDataMessagesGetStatusQueryOptions = <TData = Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDataMessagesGetStatusQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dataMessagesGetStatus>>> = ({ signal }) => dataMessagesGetStatus(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DataMessagesGetStatusQueryResult = NonNullable<Awaited<ReturnType<typeof dataMessagesGetStatus>>>
export type DataMessagesGetStatusQueryError = AxiosError<unknown>


export function useDataMessagesGetStatus<TData = Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dataMessagesGetStatus>>,
          TError,
          Awaited<ReturnType<typeof dataMessagesGetStatus>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataMessagesGetStatus<TData = Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dataMessagesGetStatus>>,
          TError,
          Awaited<ReturnType<typeof dataMessagesGetStatus>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataMessagesGetStatus<TData = Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the ISDS delivery status of a recorded data message
 */

export function useDataMessagesGetStatus<TData = Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetStatus>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDataMessagesGetStatusQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get a single recorded data message by id (no ISDS refresh)
 */
export const dataMessagesGetById = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DataMessageDto>> => {
    
    
    return axios.default.get(
      `/data-messages/messages/${id}`,options
    );
  }




export const getDataMessagesGetByIdQueryKey = (id?: string,) => {
    return [
    `/data-messages/messages/${id}`
    ] as const;
    }

    
export const getDataMessagesGetByIdQueryOptions = <TData = Awaited<ReturnType<typeof dataMessagesGetById>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetById>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDataMessagesGetByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dataMessagesGetById>>> = ({ signal }) => dataMessagesGetById(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DataMessagesGetByIdQueryResult = NonNullable<Awaited<ReturnType<typeof dataMessagesGetById>>>
export type DataMessagesGetByIdQueryError = AxiosError<unknown>


export function useDataMessagesGetById<TData = Awaited<ReturnType<typeof dataMessagesGetById>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dataMessagesGetById>>,
          TError,
          Awaited<ReturnType<typeof dataMessagesGetById>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataMessagesGetById<TData = Awaited<ReturnType<typeof dataMessagesGetById>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dataMessagesGetById>>,
          TError,
          Awaited<ReturnType<typeof dataMessagesGetById>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataMessagesGetById<TData = Awaited<ReturnType<typeof dataMessagesGetById>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetById>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a single recorded data message by id (no ISDS refresh)
 */

export function useDataMessagesGetById<TData = Awaited<ReturnType<typeof dataMessagesGetById>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataMessagesGetById>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDataMessagesGetByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



